### ISSUE TITLE
Issue with grdclip

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt#4162] opened 2020-09-04 06:46 UTC
I run the following example from the [grdclip docs](https://docs.generic-mapping-tools.org/latest/grdclip.html)

`gmt grdclip @classes.nc -Gnew_classes.nc -Si25/30/99 -Si35/39/55 -Sr17/11 -Sb10/0 -V`

(I add the @ in the file name).

Is the with error in -Si a bug? Or this was modified (and them the example should be modified)?

In another script I have this command and I have errors also with -Sb and -Sa. In previous versions (I think GMT5) it worked fine.
`	gmt grdclip %CUT% -G%CUT% -Sb3/10 -Si3/12/20 -Si12/22/30 -Sa22/40 -Vi`

![image](https://user-images.githubusercontent.com/17908951/92207361-788c8400-ee5f-11ea-90e1-758a57391677.png)

OS: Win64 GMT6.1.1.

**Comment by PaulWessel** [comment] 2020-09-04 16:51
I get the same error you do.  Will have a look after the breakfast routine...

**Comment by PaulWessel** [comment] 2020-09-04 20:55
There is no such file.  Only the files with a leading @ are actual files in the cache.  Most of our examples involve imaginary data sets and the commands cannot be tried as is.  We would  like to improve that but it is a long path ahead.  Adding a @ will not make the file appear, obviously.

**Comment by PaulWessel** [comment] 2020-09-04 20:56
However, if you have an example with a file that fails to do what the docs say, please post as an issue.

**Comment by Esteban82** [comment] 2020-09-05 10:10
Ok. I addapt it to the grid of the example 2. 
`gmt grdclip @HI_topo_02.nc -Gnew_classes.nc -Sb0/1 -Si0/2/10 -Sa2/1.9`

**Comment by seisman** [comment] 2020-10-07 10:10
The issue is related to changes in PR #2422 by @joa-quim.

**Comment by Esteban82** [comment] 2020-10-07 15:16
Ok. So now it is not possible to reclassified values as in the second example of the docs (-Si25/30/99 -Si35/39/55). 

I have an script to create an [Aspect-Slope map that](https://www.researchgate.net/publication/266214885_Color_representation_of_aspect_and_slope_simultaneously) that use this module. I think that I would have to add an extra step. First, collapse all the range values, and then replace it with (grdclip -Sr).

**Comment by seisman** [comment] 2020-10-09 01:16
@PaulWessel @joa-quim Please check if we should revert the changes in #2422.

**Comment by PaulWessel** [comment] 2020-10-09 17:22
yes, on my to-do list.

**Comment by joa-quim** [comment] 2020-10-09 19:22
I had a quick look yesterday to this and don't remember why I did it. Have a vague recall that it was triggered by a crash but looking at it I don't see how. Anyway the patch was silly as we should no restrict the values the user wants to put in the clipped zone, so, yes, those changes should be reverted.

**Comment by PaulWessel** [comment] 2020-10-09 19:31
Any easy way to revert, @seisman ?

**Comment by seisman** [comment] 2020-10-09 19:33
No easy way to revert, because the changes in #2422 were changed again after that PR was merged.

**Comment by joa-quim** [comment] 2020-10-09 19:44
Just commit a new one with the added lines removed.

**Closed** 2020-10-09 22:36 UTC
Labels: bug
