### ISSUE TITLE
NaN in the remote earth relief files

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2920] opened 2020-03-16 00:16 UTC
Run 
```
gmt grd2xyz -R116/120/34/39 @earth_relief_30s > data.txt
```
and you'll see some NaNs in `data.txt`. Is it a bug?

**Comment by PaulWessel** [comment] 2020-03-16 00:18
Known problem in @earth_relief_15s and Scripps is working on a new version.  I will check with them on status.  Once fixed we will recreate the lower resolutions.

**Comment by PaulWessel** [comment] 2020-03-16 02:27
So version 2.1 was placed on their ftp on Feb 10 but they did not let us know and we did not check.  We may wish to periodically check that site.
I am working on rebuilding the files now.

**Comment by PaulWessel** [comment] 2020-03-16 03:39
Not smooth sailing yet.  Will need to revisit some of the resolutions later:

```
pwessel@macnut:~/GMTdev/gmtserver-admin/scripts-> srv_downsampler.sh earth_relief.recipe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6259M  100 6259M    0     0  9370k      0  0:11:24  0:11:24 --:--:-- 13.5M
Convert SRTM15+V2.1.nc to earth_relief_15s.grd=ns
Down-filter SRTM15+V2.1.nc to earth_relief_30s.grd=ns
Down-filter SRTM15+V2.1.nc to earth_relief_01m.grd=ns
Down-filter SRTM15+V2.1.nc to earth_relief_02m.grd=ns
Down-filter SRTM15+V2.1.nc to earth_relief_03m.grd=ns
grdfilter [ERROR]: gmt_M_err_trap: -127
grdfilter (gmt_api.c:4975(api_export_grid)): NetCDF: Bad chunk sizes. [earth_relief_03m.grd=ns]
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
Down-filter SRTM15+V2.1.nc to earth_relief_04m.grd=ns
grdfilter [ERROR]: gmt_M_err_trap: -127
grdfilter (gmt_api.c:4975(api_export_grid)): NetCDF: Bad chunk sizes. [earth_relief_04m.grd=ns]
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
Down-filter SRTM15+V2.1.nc to earth_relief_05m.grd=ns
grdfilter [ERROR]: gmt_M_err_trap: -127
grdfilter (gmt_api.c:4975(api_export_grid)): NetCDF: Bad chunk sizes. [earth_relief_05m.grd=ns]
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_WRITE_ERROR (19)
Down-filter SRTM15+V2.1.nc to earth_relief_06m.grd=ns
Down-filter SRTM15+V2.1.nc to earth_relief_10m.grd=ns
Down-filter SRTM15+V2.1.nc to earth_relief_15m.grd=ns
Down-filter SRTM15+V2.1.nc to earth_relief_20m.grd=ns
Down-filter SRTM15+V2.1.nc to earth_relief_30m.grd=ns
```

**Comment by PaulWessel** [comment] 2020-03-16 08:26
All files updated and uploaded to gmtserver.  There are no longer any NaNs.  However, brook says there is an issue at 80N that is yet to be addressed.  Depending on access time I expect tests will eventually start failing as the PS of all earth_relief_* plots will differ.  We can refresh these in a few days.

**Comment by seisman** [comment] 2020-03-16 13:39
The gmtserver update scripts stilll doesn't work as expected. It gives the following error:
```
error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed
```
I've run `git pull` manually to update the gmtserver-admin repository on the GMT server.

**Comment by seisman** [comment] 2020-03-16 19:57
Two things to be done:

- Update the earth_relief_60m.grd file
- Upload the new earth relief data to the FTP server

**Comment by PaulWessel** [comment] 2020-03-16 20:02
OK, the earth_relief_60m.grd is a legacy duplicate of earth_relief_01d.grd.  I guess we need to keep that going forward.. Done
ftp: Done.

**Comment by seisman** [comment] 2020-03-17 00:25
This is the information when downloading earth relief file.
```
gmt [NOTICE]: earth_relief_30m: Download file from the GMT data server [data set size is 363K].
gmt [NOTICE]: Earth Relief at 30x30 arc minutes obtained by Gaussian Cartesian filtering (55 km fullwidth) of SRTM15+V2.1 [Tozer et al., 2019]20m.
```
What does the`20m` mean at the end of the second line?

**Comment by PaulWessel** [comment] 2020-03-17 00:38
Hm, will check.  Recently changed those lines to use GMT_Report...

**Comment by PaulWessel** [comment] 2020-03-17 00:45
The string printed out is listed verbatim in gmt_remote.h and has no trailing 20m. However, I note the "20m" is the very next structure element's first string.  This is a static struct with constants.  Is this from the server or from you running a command locally.  Most of these strings increased by 2 characters (version number) - try wiling and rebuilding and do the download again.

**Comment by PaulWessel** [comment] 2020-03-17 01:04
Can confirm I get the same message.  Now trying Xcode debug.

**Comment by PaulWessel** [comment] 2020-03-17 01:11
OK, that string is 128 char and that is the size of our char string,  So the \0 is lost.  Fixing now.

**Comment by seisman** [comment] 2020-03-17 02:05
We also need to update the original PS files of some failing tests.

**Comment by PaulWessel** [comment] 2020-03-17 02:06
OK, fine to leave this open until then.  I will force redownload to my machine and run tests now.

**Comment by PaulWessel** [comment] 2020-03-17 02:35
OK to close now?

**Closed** 2020-03-17 02:39 UTC
Labels: bug

**Comment by joa-quim** [comment] 2020-04-21 22:22
@mithun890 don't use this thread to ask questions. We have a forum for that.
