### ISSUE TITLE
backtracker

### ISSUE THREAD

**Issue by f-i** [GenericMappingTools/gmt#1436] opened 2019-08-25 22:27 UTC
**Description of the problem**
Hi, thank you for developing and sharing the great spotter tools! I updated GMT to the lastest dev today. When I run

**Full script that generated the error**

```
echo "0 1" |backtracker -Db -E0/0/90
```
, I get

**Full error message**

```
backtracker [ERROR]: GMT_LOGIC_BUG: gmt_scanf() called with invalid expectation.
backtracker [ERROR]: Could not decode 0, return NaN.
backtracker [ERROR]: GMT_LOGIC_BUG: gmt_scanf() called with invalid expectation.
backtracker [ERROR]: Could not decode 0, return NaN.
```

**System information**

* Operating system: Linux
* Version of GMT: 6.1.0_36fbdf9_2019.08.25

**Comment by PaulWessel** [comment] 2019-08-25 22:47
Sorry, thanks for posting here.  I cannot reproduce that. I get

```
echo "0 1" | gmt backtracker -Db -E0/0/90
-0.993306965794    0    

gmt --version
6.1.0_1ef4ed2_2019.08.25
```
Could you please tell me your operating system and run gmt backtracker with -Vd to see if we can learn anything.

**Comment by f-i** [comment] 2019-08-25 23:14
Hi Prof. Wessel,

Thank you for your quick reply.

I deleted my build subfolder, and re-run cmake, make, make install. And it works now. Thanks! I have no idea what happened. It might be caused by some recently-updated dependency package. Sorry for bothering you.

My OS is 5.2.9-gentoo. Here is the output from `gmt backtracker -Vd` before I re-installed GMT:

> gmt [DEBUG]: Obtained the ppid from parent: 3079
gmt [DEBUG]: Enter: gmtinit_new_GMT_ctrl
gmt [DEBUG]: GMT->session.SHAREDIR = /opt/gmt/share
gmt [DEBUG]: GMT->session.HOMEDIR = /home/g
gmt [DEBUG]: GMT->session.USERDIR = /home/g/.gmt [created]
gmt [DEBUG]: GMT->session.CACHEDIR = /home/g/.gmt/cache [created]
gmt [DEBUG]: GMT: 0. Will try to find subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt
gmt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
gmt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /home/g/.gmt
gmt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /home/g/.gmt/postscriptlight
gmt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /opt/gmt/share/postscriptlight
gmt [DEBUG]: GMT: 5. gmt_getsharepath failed
gmt [DEBUG]: Map distance calculation will be Cartesian
gmt [DEBUG]: Exit:  gmtinit_new_GMT_ctrl
gmt [DEBUG]: Enter: New_PSL_Ctrl
gmt [DEBUG]: Exit:  New_PSL_Ctrl
gmt [DEBUG]: Enter: gmt_manage_workflow
gmt [DEBUG]: Exit : gmt_manage_workflow
gmt [DEBUG]: Enter: PSL_beginsession
gmt [DEBUG]: Exit : PSL_beginsession
gmt [DEBUG]: Enter: PSL_setdefaults
gmt [DEBUG]: Exit : PSL_setdefaults
gmt [DEBUG]: Enter: gmtlib_io_init
gmt [DEBUG]: Exit : gmtlib_io_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: The PROJ_GEODESIC set to Vincenty
gmt [DEBUG]: Enter: gmt_getdefaults
gmt [DEBUG]: Look for file /home/g/gmt.conf
gmt [DEBUG]: Look for file /home/g/.gmt/gmt.conf
gmt [DEBUG]: Look for file /home/g/.gmt/server/gmt.conf
gmt [DEBUG]: Look for file /home/g/.gmt/cache/gmt.conf
gmt [DEBUG]: Could not find file gmt.conf
gmt [DEBUG]: Exit:  gmt_getdefaults
gmt [DEBUG]: Enter: gmtlib_plot_C_format
gmt [DEBUG]: Exit:  gmtlib_plot_C_format
gmt [DEBUG]: Enter: gmtinit_get_history
gmt [DEBUG]: GMT_Create_Session initialized GMT structure
gmt [DEBUG]: Shared Library # 0 (core). Path = libgmt.so
gmt [DEBUG]: Loading core GMT shared library: libgmt.so
gmt [DEBUG]: Loading GMT plugins from: /opt/gmt/lib64/gmt/plugins
gmt [DEBUG]: Shared Library # 1 (supplements). Path = /opt/gmt/lib64/gmt/plugins/supplements.so
backtracker [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
backtracker (gmtlib_free_tmp_arrays): tried to free unallocated memory
gmt [DEBUG]: Entering GMT_Destroy_Session

>

**Comment by PaulWessel** [comment] 2019-08-25 23:21
No worries, closing this issue.

**Closed by PaulWessel** 2019-08-25 23:21 UTC
