### ISSUE TITLE
Runing from externals is broken on Linux

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3233] opened 2020-05-03 17:44 UTC
https://travis-ci.org/github/GenericMappingTools/GMT.jl/builds/682647264

![image](https://user-images.githubusercontent.com/537321/80921398-1a934700-8d6e-11ea-8035-b5375bdc3e57.png)

**Comment by joa-quim** [comment] 2020-05-03 18:04
And when I try to build in WSL, it now
```
j@Marilu:~/programs/build$ make -j10
Scanning dependencies of target gen_gmt_suppl_supplements_headers
Scanning dependencies of target gen_gmt_headers
Scanning dependencies of target script2verbatim
Scanning dependencies of target gshhg_version
[  2%] Generating gmt_keycases.h, gmt_keywords.h
[  2%] Building C object src/CMakeFiles/script2verbatim.dir/script2verbatim.c.o
[  2%] Generating gmt_core_moduleinfo.h
[  2%] Generating gmt_supplements_moduleinfo.h
[  2%] Building C object src/CMakeFiles/gshhg_version.dir/gshhg_version.c.o
[  2%] Generating gmt_dimensions.h
CMake Error at /mnt/c/progs_cygw/GMTdev/gmt5/master/cmake/modules/GmtGenExtraHeaders.cmake:119 (list):
  list does not recognize sub-command JOIN
Call Stack (most recent call first):
  /mnt/c/progs_cygw/GMTdev/gmt5/master/cmake/modules/GmtGenExtraHeaders.cmake:130 (gen_gmt_moduleinfo_h)

```

**Comment by seisman** [comment] 2020-05-03 18:18
list JOIN was introduced in CMake 3.12. I need to find another way to support older CMake versions.

**Comment by joa-quim** [comment] 2020-05-03 19:30
OK, that fixed the WSL build, but the Travis build is still broken.

**Comment by seisman** [comment] 2020-05-03 19:41
The GMT build is successful, so I believe the command "gmt grdmath" should be fine.

Then the question is why GMT.jl cannot find grdmath in the shared library. 

Does it work for you locally? Can GMT.jl find other modules?

**Comment by joa-quim** [comment] 2020-05-03 20:10
As can be seen from the failing log it only finds the modules inside the supplements. Not in core.
And, yes it runs fine locally.

**Comment by joa-quim** [comment] 2020-05-03 20:20
Actually it also fails for the same reason in my WSL GMT build.

**Comment by PaulWessel** [comment] 2020-05-03 21:30
All those symbols are exported in the main shared library, at least on Unix.  Can you list the symbols in your DLL and see if GMT_grdmath is there?

**Comment by joa-quim** [comment] 2020-05-03 21:56
DLL's? It's in Linux (and quite likely OSX) that is broken. On Win it works fine.

**Comment by PaulWessel** [comment] 2020-05-03 21:56
Sorry, OK, so do nm -g libgmt.so | grep GMT_grdmath

**Comment by joa-quim** [comment] 2020-05-03 21:57
BTW, can you try it?

**Comment by PaulWessel** [comment] 2020-05-03 22:02
What specifically do you want me to try? Isn't it easy for you to run the nm command?

**Comment by joa-quim** [comment] 2020-05-03 22:09
Any GMT julia command. Gee you only have to replace ` by " and pretend its a MEX call
```
gmt("gmtinfo",[1,2,3,4])
```

And the ``GMT_xxx`` are listed in ``libgmt.so``

**Comment by PaulWessel** [comment] 2020-05-03 22:15
Last time I tried to install Julia, GMT.jl and run something we ran into tons of issues that took hours.  Give that Idont have hours I am happy to run a script that installs everything and then try a command, but I dont want to spend hours installing, trail-and-error, etc etc since I do not use nor know Julia.  Also in the middle of a family FaceTime call so going back and forth.,.,

**Comment by joa-quim** [comment] 2020-05-03 22:20
On Linus at least, I bet the gmtmex is broken too.

**Comment by PaulWessel** [comment] 2020-05-03 22:21
I've done a lot of debugging in gmtmex the last few days (remember the strip image) and no problem.  Are you saying this stopped working today?

**Comment by joa-quim** [comment] 2020-05-03 22:30
No, I don't know when this stop working. A couple of weeks ago it was still working. That was when I last run the Travis CI Julia tests.

**Comment by PaulWessel** [comment] 2020-05-03 22:42
The only time we have had issues with not finding modules has been on Windows when we have violated some DLL exporting rule.  On Linux and macOS things are exported unless static, and in the redo of the glue we made sure every module has MSC_EXTERN in front of their declaration.  So might there be something in the CI script that need to change following the changes in the glue etc?

**Comment by joa-quim** [comment] 2020-05-03 22:47
It's not the CI script. It fails likewise in my WSL GMT build.

**Comment by PaulWessel** [comment] 2020-05-03 22:50
Maybe you said this already... The WSL build of GMT works fine in a bash script, but when called from Julia it cannot find those modules?

**Comment by joa-quim** [comment] 2020-05-03 22:53
The error message is perhaps misleading. When Ctr-D'it it prints

```
julia> gmtinfo([1,2,3,4])
GMT [ERROR]: Shared GMT module not found: gmtinfo

===  GMT supplements: The official supplements to the Generic Mapping Tools  ===

Module name:     Purpose of geodesy module:
----------------------------------------------------------------
earthtide        Compute grids or time-series of solid Earth tides
gpsgridder       Interpolate GPS strains using Green's functions for elastic deformation
velo             Plot velocity vectors, crosses, and wedges
...

Error returned from GMT API: GMT_NOT_A_VALID_MODULE (44)
^C^C^Cgmtinfo [ERROR]: No input data found!
ERROR: InterruptException:
```
So it does land inside ``gmtinfo`` but it's not seeing the input data.

**Comment by joa-quim** [comment] 2020-05-03 22:58
```
julia> G = GMT.peaks();

julia> gmt("grdredpol", G)
title: Anomaly reducted to the pole
command: grdredpol @GMTAPI@-S-I-G-G-G-N-000002 -G@GMTAPI@-S-O-G-G-G-N-000003
Gridline node registration used
x_min: -3.0     x_max :3.0      x_inc :0.125    n_columns :49
y_min: -3.0     y_max :3.0      y_inc :0.125    n_rows :49
z_min: -2.6314243430850015e32   z_max :2.02344626385051e32


julia> gmt("grdinfo", G)
GMT [ERROR]: Shared GMT module not found: grdinfo
```

**Comment by joa-quim** [comment] 2020-05-04 00:57
OK, I went back to my old Mac, installed GMT and Julia and all works fine.
Shit is then it's then restricted to Linux, and I renew my bet that gmtmex wont work in it either.

**Comment by PaulWessel** [comment] 2020-05-04 02:14
Building GMT in WSL and running on command line works fine (core and supplements).  So things are in the shared library and it would seem the problem is on the calling side?

**Comment by joa-quim** [comment] 2020-05-04 02:34
What do you mean the "calling side"?

**Comment by joa-quim** [comment] 2020-05-04 02:50
When I put debug prints inside ``gmtapi_get_shared_module_keys()`` either ``func`` is NULL or when it isn't then the ``keys`` are NULL. So it never reads the keys and the ``Shared GMT module not found:`` message is misleading.

**Comment by PaulWessel** [comment] 2020-05-04 02:51
If gmt grdinfo - works in WSL bash command line then clearly the GMT_grdinfo function is exported by the libgmt.so shared library.  Now, my understanding is that GMT.jl will call GMT_Module for "grdinfo" or similar via its C wrapper.  That is failing I think you said.  I am not sure what the Julia gmt ("grdinfo", ...) function does but the GMT shared library has all the exported functions.

**Comment by joa-quim** [comment] 2020-05-04 02:54
See my message above and recall that it works on Win & Mac so it isn't the Julia fault.

**Comment by PaulWessel** [comment] 2020-05-04 02:55
But you are not calling gmtapi_get_shared_module_keys yourself right? You mean inside gmt_api.c right.  And the function name that is built from 
	snprintf (function, GMT_LEN64, "%s_module_keys", API->lib[lib_no].name);
says
core_module_keys ?  That one is exported

gmt_core_glue.c:EXTERN_MSC const char *core_module_keys (void *API, char *candidate) {

**Comment by PaulWessel** [comment] 2020-05-04 02:56
OK, can you verify that it is the call to lookup core_module_keys function that fails?

**Comment by joa-quim** [comment] 2020-05-04 02:57
Yes, it is.

**Comment by PaulWessel** [comment] 2020-05-04 02:58
And when I run `nm -g libgmt.so | grep core_ `it finds it as an exported symbol.  Strange.  Can you print out the name of the library as well so we are sure it is trying to open the core library and lookup that function?

**Comment by joa-quim** [comment] 2020-05-04 03:07
Where is the library's name?  ``API->lib[lib_no].handle`` is a ``void *``

**Comment by PaulWessel** [comment] 2020-05-04 03:19
API->lib[lib_no].path is full path to the library that dlopen is trying to open
API->lib[lib_no].name is the name of the library.

**Comment by joa-quim** [comment] 2020-05-04 03:31
WSL prints:
```
julia> basemap(R=(0,10,0,10), proj=:linear)
MERDAAAA_1 path=libgmt.so  name=core
MERDA--1-- keys  (null)
MERDAAAA_1 path=/home/j/programs/lib/gmt/plugins/supplements.so  name=supplements
MERDAAAA_2   (null)   psbasemap
```
So path to libgmt.so seems wrong
Windows prints:
```
julia> basemap(R=(0,10,0,10), proj=:linear)
MERDAAAA_1 path=gmt.dll  name=core
MERDAAAA_2   >X},>DA@AD)   psbasemap
MERDA--1-- keys  >X},>DA@AD)
```
Don't understand that ``gmt.dll``. Should be ``gmt_w64.dll`` but this is enough for today.

**Comment by PaulWessel** [comment] 2020-05-04 18:26
See man dlopen to learn how to examine failure to open the shared library.  Also, try to set LD_LIBRARY_PATH to the directory with libgmt.so and see if that works - if so then this is a path issue.

**Comment by joa-quim** [comment] 2020-05-04 18:45
The Travis [CI script](https://github.com/GenericMappingTools/GMT.jl/blob/master/.travis.yml) for Julia has always set LD_LIBRARY_PATH  but now it's not enough.
I need to find where ``API->lib[lib_no].path`` is set to try debug it. But mind you I'm trying to debug Linux on Win.

**Comment by PaulWessel** [comment] 2020-05-04 18:50
In gmtapi_init_sharedlibs.

	API->lib[0].name = strdup ("core");
	API->lib[0].path = strdup (GMT_CORE_LIB_NAME);

See discussion for dlopen_special. I wonder if that special case does not apply when externals are calling gmt - despite working for macos and Windows.  Experiment: Change line 988 to the same dlopen command as is used for supplements.

**Comment by joa-quim** [comment] 2020-05-04 19:15
Made this
```
#undef GMT_CORE_LIB_NAME
#define GMT_CORE_LIB_NAME "/home/j/programs/lib/libgmt.so"
```
but no way. So it's not a path issue.

**Comment by PaulWessel** [comment] 2020-05-04 21:18
If dlopen_special returns NULL, try calling printf (stderr, "%s\n", dlerror());

So you (and gmtmex) calls GMT_Call_Module for varous modules.  We first call GMT_Create_Session when all the shared libs are found and opened.  I wonder if there is a difference when externals are using libgmt and when gmt.c is using libgmt sinc we are building that one at the same time.  Perhaps our special opening of the core library is wrong when externals are calling it and we should use dlopen the same way we do for supplements.  We have API->external to check I think.

**Comment by PaulWessel** [comment] 2020-05-04 21:26
Or maybe try to comment out lines 988-922 and see what happens.

**Comment by seisman** [comment] 2020-05-04 21:30
I also tried Julia 1.4.1 + GMT master + GMT.jl master, and I got a slightly different error. Unlike @joa-quim's command, I got the grid information although GMT says grdinfo is not found.
```
julia> gmt("grdinfo", "@earth_relief_01d")
GMT [ERROR]: Shared GMT module not found: grdinfo

===  GMT supplements: The official supplements to the Generic Mapping Tools  ===

Module name:     Purpose of geodesy module:
----------------------------------------------------------------
earthtide        Compute grids or time-series of solid Earth tides
gpsgridder       Interpolate GPS strains using Green's functions for elastic deformation
velo             Plot velocity vectors, crosses, and wedges

...
Module name:     Purpose of x2sys module:
----------------------------------------------------------------
x2sys_binlist    Create bin index listing from track data files
x2sys_cross      Calculate crossovers between track data files
x2sys_datalist   Extract content of track data files
x2sys_get        Get track listing from track index database
x2sys_init       Initialize a new x2sys track database
x2sys_list       Extract subset from crossover data base
x2sys_merge      Merge an updated COEs table (smaller) into the main table (bigger)
x2sys_put        Update track index database from track bin file
x2sys_report     Report statistics from crossover data base
x2sys_solve      Determine least-squares systematic correction from crossovers
Error returned from GMT API: GMT_NOT_A_VALID_MODULE (44)
/mnt/home/tiandong/.gmt/server/earth_relief_01d.grd: Title: Earth Relief at 01 arc degree
/mnt/home/tiandong/.gmt/server/earth_relief_01d.grd: Command: grdfilter SRTM15+V2.1.nc -Fg111.2 -D1 -I01d -rg -Gearth_relief_01d.grd=ns --IO_NC4_DEFLATION_LEVEL=9 --IO_NC4_CHUNK_SIZE=4096 --PROJ_ELLIPSOID=Sphere
/mnt/home/tiandong/.gmt/server/earth_relief_01d.grd: Remark: Obtained by Gaussian Cartesian filtering (111.2 km fullwidth) from SRTM15+V2.1.nc [Tozer et al., 2019; http://dx.doi.org/10.1029/2019EA000658]
/mnt/home/tiandong/.gmt/server/earth_relief_01d.grd: Gridline node registration used [Geographic grid]
/mnt/home/tiandong/.gmt/server/earth_relief_01d.grd: Grid file format: ns = GMT netCDF format (16-bit integer), CF-1.7
/mnt/home/tiandong/.gmt/server/earth_relief_01d.grd: x_min: -180 x_max: 180 x_inc: 1 name: longitude n_columns: 361
/mnt/home/tiandong/.gmt/server/earth_relief_01d.grd: y_min: -90 y_max: 90 y_inc: 1 name: latitude n_rows: 181
/mnt/home/tiandong/.gmt/server/earth_relief_01d.grd: z_min: -8592 z_max: 5559 name: elevation (m)
/mnt/home/tiandong/.gmt/server/earth_relief_01d.grd: scale_factor: 1 add_offset: 0
/mnt/home/tiandong/.gmt/server/earth_relief_01d.grd: format: netCDF-4 chunk_size: 181,181 shuffle: on deflation_level: 9
```

**Comment by seisman** [comment] 2020-05-04 21:31
FYI, pygmt.grdinfo works with the same GMT build.

**Comment by seisman** [comment] 2020-05-04 21:48
Just did a bisect search. GMT.jl works with GMT f14df9d1e07c490412b7db07f290e1196706d201 but fails with c8e1c94596066c90da368186a1fb18b1710c3cb5, i.e., changes in https://github.com/GenericMappingTools/gmt/pull/3133 breaks GMT.jl.

**Comment by PaulWessel** [comment] 2020-05-04 21:51
I think the old ways had the supplements have links to the core modules (i.e., we had the EXPORT_MSC prototypes for core modules included in supplements,so.  But that makes no sense to me, i.e., that every external library must include those prototypes since they are exported by libgmt.

**Comment by PaulWessel** [comment] 2020-05-04 22:04
@seisman, are you able to tell which shared library it finds the core function you tried? Lib = 0 is libgmt, while lib = 1 is supplements.so.

**Comment by joa-quim** [comment] 2020-05-04 22:14
```
fprintf (stderr, "MERDAAAA_22  %s\n", dlerror());
```
results in
```
MERDAAAA_22  julia: undefined symbol: core_module_keys
```

**Comment by PaulWessel** [comment] 2020-05-04 22:19
OK, here is my experience with gmtmex on macos:

I am using the external-lib-access branch.  It delays opening the libgmt until we need to.  This failes with the message of image not found by dlopen.  It tries to open libgmt.dylib but cannot find it.  I then did like @joa-quim and hardwired the path to /opt/gmt/lib/libgmt.dylib.  Now it works.

As for MERDAAAA_2 Iway too many A's here I think - I sense anger):

nm -g libgmt.dylib | grep core_module_keys
000000000026a560 T _core_module_keys

Problem is I suspect you still cannot find libgmt.so and hence it looks in supplements.so instead and of course cannot find.

**Comment by joa-quim** [comment] 2020-05-04 22:24
> As for MERDAAAA_2 Iway too many A's here I think - I sense anger):
 
Yesterday at 5 oclok probably but no, ``MERDA`` is my printf debug string. Easy to remember and grep back when cleaning is needed. When number of debug messages grow, so does the number of ``AAA```

**Comment by PaulWessel** [comment] 2020-05-04 22:27
If I set DYLD_LIBRARY_PATH to /opt/gmt/lib and just use libgmt.dylib then it fails.  SO for me on macos this is clearly a path finding issue.

**Comment by joa-quim** [comment] 2020-05-04 22:27
Why the leading underscore? I get
```
j@Marilu:~/programs/lib$ nm -g libgmt.so | grep core_module_keys
00000000001e2d50 T core_module_keys
```

**Comment by PaulWessel** [comment] 2020-05-04 22:29
That may be OS specific.

**Comment by PaulWessel** [comment] 2020-05-04 22:34
On my ubuntu it is like yours, no underscore.  That is not the issue.  The function is exported by the library.

**Comment by PaulWessel** [comment] 2020-05-04 22:38
Looking at gmtapi_init_sharedlibs, I wonder if we should try to set the path to the core library as well.  It would be the same scheme as for the plugin except no plugin/gmt part of the path.

**Comment by joa-quim** [comment] 2020-05-04 22:39
But that's what we both tried.

**Comment by PaulWessel** [comment] 2020-05-04 22:39
But @joa-quim, you said when you hardwired path[0] to be the correct libgmt.so path (pls check), it still failed? Whereas for me that worked?

**Comment by PaulWessel** [comment] 2020-05-04 22:39
> But that's what we both tried.

and it worked for me.

**Comment by joa-quim** [comment] 2020-05-04 22:41
Don't know about unix but on Win we can have a "no symbol found" for a bloody *depen-of-depend-of-depend-of-dependency*. It makes it really hard to find out who's in fact de culprit.

**Comment by joa-quim** [comment] 2020-05-04 22:43
Have to make a break to check if MB is still working for tomorrow's zoom class.

**Comment by joa-quim** [comment] 2020-05-04 23:07
```
julia> basemap(R=(0,10,0,10), proj=:linear)
MERDAAAA_1 path=/home/j/programs/lib/libgmt.so  name=core
MERDAAAA_22  julia: undefined symbol: core_module_keys
```

**Comment by PaulWessel** [comment] 2020-05-04 23:09
And is the path successful in opening the library? Or is the message coming at the end after it cannot find it in any library.

**Comment by joa-quim** [comment] 2020-05-04 23:13
``MERDAAAA_22`` is printed when

```
	snprintf (function, GMT_LEN64, "%s_module_keys", API->lib[lib_no].name);
fprintf(stderr, "MERDAAAA_1 path=%s  name=%s\n", API->lib[lib_no].path, API->lib[lib_no].name);
	if (API->lib[lib_no].handle)
	/* Here the library handle is available; try to get pointer to specified module */
	*(void **) (&func) = dlsym (API->lib[lib_no].handle, function);
	//if (func) keys = (*func) (API, module);
	if (func) {
		keys = (*func) (API, module);
fprintf(stderr, "MERDAAAA_2   %s   %s\n", keys, module);
	}
	else
fprintf (stderr, "MERDAAAA_22  %s\n", dlerror());
	return (keys);
```

**Comment by joa-quim** [comment] 2020-05-04 23:18
The key question is why?
```
MERDAAAA_1 path=/home/j/programs/lib/libgmt.so  name=core
MERDAAAA_22  julia: undefined symbol: core_module_keys
```
when
```
nm -g /home/j/programs/lib/libgmt.so | grep core_module_keys
00000000001e2d50 T core_module_keys
```

**Comment by PaulWessel** [comment] 2020-05-04 23:25
OK, so it finds the library libgmt.so, it successfully opens it, but unable to find core_module_keys via dlsym, despite that symbol exists in the .so.

See https://stackoverflow.com/questions/37104928/dlsym-returns-null-even-though-the-symbol-exists.

I wonder if your LInux is now starting to use these __atrribute__ settings just like we define EXTERN_MSC. ?

**Comment by joa-quim** [comment] 2020-05-04 23:38
But is it different between ``supplements.so`` and ``libgmt.so``? I can access the symbols in supplements via Julia.

**Comment by PaulWessel** [comment] 2020-05-04 23:41
I do not understand why it is behaving this way.  I am grasping at straws.  We need someone who understands this on the Linux side.  Unfortunately, I have a faculty meeting this pm so need to drop GMT for a bit.

**Comment by joa-quim** [comment] 2020-05-05 00:01
Adding that ``__attribute__ ((visibility("default")))`` declaration to ``EXTERN_MSC`` makes no difference.

**Comment by PaulWessel** [comment] 2020-05-05 00:03
OK did you try my branch (which is not using dlopen_special) or are you using master (which is opening libgmt.so with dlopen_special)?

**Comment by joa-quim** [comment] 2020-05-05 00:08
Master

**Comment by PaulWessel** [comment] 2020-05-05 00:09
From dlopen man page:

`If filename is NULL, then the returned handle is for the main program. `

This makes sense for gmt.c which is the main program for the command line version.  However, in your and gmtmex case we there is not any main program for which libgmt is the child of whatever.  So I think my branch is correct for externals, but path seems to be a problem.

**Comment by PaulWessel** [comment] 2020-05-05 00:10
Try the external-lib-access and be prepared (if it fails) to insert your hardwired name again.  This worked for gmtmex which is the same situation you are in.

**Comment by joa-quim** [comment] 2020-05-05 00:22
Yes, it works and with no need to hardwire the path. But it means dlopen behaves  differently in GCC and the other two compilers? Very weird.

**Comment by PaulWessel** [comment] 2020-05-05 00:24
Indeed weird, and I may need to test more with gmtmex since it failed for me without the hard path.  But your experience and my hardwired experience means this is just a matter of path setting.  I think the strategy in the branch is sound.  What say you, @seisman ?

**Comment by PaulWessel** [comment] 2020-05-05 00:40
Remember that when Florian set all this up it was meant to be a shared library for gmt.c.  Perhaps the lack of a path given was OK because NULL was passed anyway.  Now that we actually pass the path it has to be resolvable and that gets into OS specifics on LD_LIBRARY_PATH, DYLD_LIBRARY_PATH etc.  We should probably set the path as we do for the suppelments.so.

**Comment by PaulWessel** [comment] 2020-05-08 06:29
Can we close this one?

**Comment by seisman** [comment] 2020-05-08 06:35
Yes after merge #3253.

**Closed** 2020-05-09 04:21 UTC
