### ISSUE TITLE
Still custom supplements type 3

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#3180] opened 2020-04-26 12:50 UTC
I still not getting how build de MBGMT modules. I have this in a ``mggmt_module.c``
```
#include "gmt_dev.h"
#include "gmt_internals.h"
#include "mbgmt_module.h"

/* Sorted array with information for all mbgmt modules */

static struct GMT_MODULEINFO modules[] = {
	{"mbareaclean", "mbareaclean", "mbgmt", "Automatically flag bad beams in swath sonar bathymetry data", ""},
	{"mbcontour",   "mbcontour", "mbgmt",  "Plot swath bathymetry, amplitude, or backscatter",  "CC(,>X}"},
	{"mbclean_j",   "mbclean_j","mbgmt", "Identifies and flags artifacts in swath sonar bathymetry data", ""},
	{"mbflags",     "mbflags","mbgmt", "Update the flags .esf file from external file", ""},
	{"mbgetdata",   "mbgetdata","mbgmt", "Get swath bathymetry, amplitude, or backscatter data into Matlab", "<D{,ND),MD}"},
	{"mbgrdtiff",   "mbgrdtiff", "mbgmt",  "Project grids or images and plot them on maps",  "<G{+,CC(,IG("},
	{"mbgrid_j",    "mbgrid_j","mbgmt", "grid bathymetry, amplitude, or sidescan data of a set of swath sonar data files", ""},
	{"mbimport",    "mbimport","mbgmt", "Get swath bathymetry, amplitude, or backscatter Image into Matlab", "<D{,CC(,MI}"},
	{"mbinfo",      "mbinfo","mbgmt", "Read a swath sonar data file and outputs some basic statistics.", "<D{,>D},>DC,>DO"},
	{"mbset",       "mbset","mbgmt", "Set values in an mbprocess parameter file", ""},
	{"mbprocess",   "mbprocess","mbgmt", "Tool for processing swath sonar bathymetry data", "ID{,OD("},
	{"mbswath",     "mbswath", "mbgmt",  "Plot swath bathymetry, amplitude, or backscatter",  "CC(,NC(,>X}"},
	{"gmtmbgrid",   "gmtmbgrid","mbgmt", "Grid table data using adjustable tension continuous curvature splines", "<D{,DD(,LG(,GG}"},
	{NULL, NULL, NULL, NULL, NULL} /* last element == NULL detects end of array */
};
```
and must be from here that it's getting the info to create the ``build/src/gmt_mbgmt_moduleinfo.h``
but it has
```
	{"", "", "mbgmt", "Plot swath bathymetry, amplitude, or backscatter", ">X}"},
	{"", "", "mbgmt", "Plot swath bathymetry, amplitude, or backscatter", "CC(,NC("},
	{"", "", "mbgmt", "Project grids or images and plot them on maps", "<G{+,CC(,IG("},
...
```
and ``gmt --help`` then prints
```
Module name:     Purpose of mbgmt module:
----------------------------------------------------------------
                 Plot swath bathymetry, amplitude, or backscatter
                 Plot swath bathymetry, amplitude, or backscatter
```

**Comment by seisman** [comment] 2020-04-26 17:26
Could you share the latest mbgmt codes, especially the CMakeLists.txt?

**Comment by joa-quim** [comment] 2020-04-26 17:36
[mbgmt.zip](https://github.com/GenericMappingTools/gmt/files/4536061/mbgmt.zip)

**Comment by seisman** [comment] 2020-04-26 17:50
1. I think your mbgmt belong to GMT supplements type 2, not type 3.
2. We expect the THIS_MODULE_CLASSIC_NAME and THIS_MODULE_MODERN_NAME macros, but your C codes (https://github.com/joa-quim/mbgmt) give THIS_MODULE_NAME. That's why your gmt_mbgmt_moduleinfo.h is incorrect. 
3. With #3177 merged, the GMT CMake scripts will automatically build gmt_mbgmt_moduleinfo.h and gmt_mbgmt_glue.c for you. So you don't need to provide mbgmt_module.c and mbgmt_module.h any more.

Please remove mbgmt_module.c and mbgmt_module.h and remove them from the CMakeLists, and try again.

**Comment by seisman** [comment] 2020-04-26 17:52
> and must be from here that it's getting the info to create the `build/src/gmt_mbgmt_moduleinfo.h`

No, the gmt_mbgmt_moduleinfo.h is built from the macros in the C codes, including

- THIS_MODULE_CLASSIC_NAME
- THIS_MODULE_MODERN_NAME
- THIS_MODULE_LIB
- THIS_MODULE_PURPOSE
- THIS_MODULE_KEYS

**Comment by joa-quim** [comment] 2020-04-26 18:49
Ok, it works now. Thanks.

**Comment by joa-quim** [comment] 2020-04-27 17:08
This one quit working. The build I have from some weeks ago works.
```
>> D = gmtmex('mbinfo -G -O -IC:\j\OT\PatchSurvezEM122PHINS\0002_20111219_175708_METEOR_EM122.mb59 -Vl')
mbinfo [INFORMATION]: Writing Data Table to Standard Output stream
One or more output arguments not assigned during call to "gmtmex".
```
Its KEYs are
> #define THIS_MODULE_KEYS	"<D{,>D},>DC,>DO" 

don't remember anymore the others but ``>D}`` should get me the needed output.

**Comment by joa-quim** [comment] 2020-04-27 18:23
Something in GMT_Put_record() is broken for externals. It prints to stdout instead of dataset

**Comment by PaulWessel** [comment] 2020-04-27 18:32
What is >DO for? I think that means if -O is given then output is changed to a dataset.   But primary output is already data set (>D}).  Also, if this is keys related then nothing has really happened to those I think?

**Comment by joa-quim** [comment] 2020-04-27 18:42
It doesn't matter if I remove either >DO or >D} it still doesn't work. And was working till about a week ago.
It's the file pointer that points stdout instead of the virtual dataset

**Comment by PaulWessel** [comment] 2020-04-27 19:01
Run in debug and see what is not hooked up:

1. What is the content of gtxt below?
```
	if (options) {	/* Only for debugging - remove this section when stable */
		gtxt = GMT_Create_Cmd (API, options);
		GMT_Report (API, GMT_MSG_DEBUG, "GMT_Encode_Options: Revised command after memory-substitution: %s\n", gtxt);
		GMT_Destroy_Cmd (API, &gtxt);	/* Only needed it for the above verbose */
	}
```

Assuming gtxt is correct, what is not being hooked up in the loop below?

```
	/* 5. Assign input sources (from MATLAB to GMT) and output destinations (from GMT to MATLAB) */
	
	for (k = 0; k < n_items; k++) {	/* Number of GMT containers involved in this module call */
		if (X[k].direction == GMT_IN) {
			if ((X[k].pos+first+1) < (unsigned int)nrhs)
				ptr = (void *)prhs[X[k].pos+first+1];
			else
				mexErrMsgTxt ("GMT: Attempting to address a prhs entry that does not exist\n");
		}
		else {
			if ((X[k].pos) < nlhs)
				ptr = (void *)plhs[X[k].pos];
			else {
				//mexErrMsgTxt ("GMT: Attempting to address a plhs entry that does not exist\n");
				ptr = alloc_default_plhs (API, &X[k]);
			}
		}
		GMTMEX_Set_Object (API, &X[k], ptr);	/* Set object pointer */
	}
```

**Comment by joa-quim** [comment] 2020-04-27 19:08
It's not in gmtmex. I'm debugging from Julia and seeing it print to stdout

**Comment by PaulWessel** [comment] 2020-04-27 19:10
Well, still need to look at why not hooking up to a dataset structure.  I do not believe I have made any changes to the i/o recently that will affect this?  I don't know exactly what you do in Julia but you must be doing something like the above to build the command string, no?

**Comment by joa-quim** [comment] 2020-04-27 22:30
``gtxt`` is fine but loop after is not executed because ``n_items = 0``. No other args than the input string.

But this, that also uses GMT_Put_record``, works fine. I don't see what could be doing different from MBGMT lib.

``gmtmex('gmtinfo lixo.txt')``

**Comment by PaulWessel** [comment] 2020-04-27 22:40
I dont know mbinfo but is it really using the GMT i/o machinery to write its output?  Did you add that later?

**Comment by joa-quim** [comment] 2020-04-27 22:42
My mbinfo uses GMT IO and I've changed it in 2 or 3 years

**Comment by joa-quim** [comment] 2020-04-27 22:46
Except for the changes obliged by

![image](https://user-images.githubusercontent.com/537321/80428219-3f586c00-88e1-11ea-8dfa-28c3e4c058d0.png)

**Comment by PaulWessel** [comment] 2020-04-27 22:49
I have two zoom conferences coming up.  Is it possible for me to build this on macOS or is it just Win only? 
There have been some changes in gmt.h and gmt_resources.h I think you have told me this affects Julia?

**Comment by PaulWessel** [comment] 2020-04-28 00:43
If n_items == 0 then the KEYS did not stick for the>D} default case.  I worry about the >DO interfering somehow, otherwise I would think the >D} should work like everywhere else.

**Comment by joa-quim** [comment] 2020-04-28 00:48
No, I found the fucker. And this time it was a  real fucker. When the THIS_MODULE_KEYS have an extra space after the last “ the KEYS in *_moduleinfo.h are EMPTY

#define THIS_MODULE_KEYS               "<D{,>D},>DC,>DO"_

Now works again

**Comment by joa-quim** [comment] 2020-04-28 01:01
For the record, this was a really nasty one. Extra blanks at the end of the ``THIS_MODULE_KEYS`` cause the ``*_moduleinfo.h`` KEYS to become EMPTY.

**Comment by seisman** [comment] 2020-04-28 01:56
It's caused by the fragile regex when building module info header files.

**Comment by PaulWessel** [comment] 2020-04-28 02:00
I take it is difficult to guard against that (e.g., trailing white space in general for those lines)?

**Comment by seisman** [comment] 2020-04-28 02:11
Among the 5 macros (THIS_MODULE_CLASSIC_NAME, THIS_MODULE_MODERN_NAME, THIS_MODULE_LIB, THIS_MODULE_LIB and THIS_MODULE_KEYS) used in building module info, only THIS_MODULE_KEYS can be empty. It's impossible to check if THIS_MODULE_KEYS is correctly parsed, but at least we can check if the other 4 macros are parsed and have unempty strings.

**Comment by PaulWessel** [comment] 2020-04-28 02:14
You mean in C? Yes, easily done at top of gmt_init_module, etc.

**Comment by seisman** [comment] 2020-04-28 02:16
I mean in the cmake macro, i.e. report errors if make variables e.g., **_this_module_classic_name** are empty.

https://github.com/GenericMappingTools/gmt/blob/6bc66af9dd425b4b7281b55643e84f64b0450703/cmake/modules/GmtGenExtraHeaders.cmake#L89-L99

**Closed** 2020-04-28 02:16 UTC
