### ISSUE TITLE
xyz2grd ignores z-column data with -f0T,1x,2f

### ISSUE THREAD

**Issue by uleysky** [GenericMappingTools/gmt#2344] opened 2019-12-26 02:53 UTC
Test file test.dat, first column is time, second - longitude, third - some z-value:
1991-01-01	0	1 
1991-01-01	1	2  
1991-01-01	2	3  
1991-01-02	0	4  
1991-01-02	1	5  
1991-01-02	2	6  
1991-01-03	0	7  
1991-01-03	1	8  
1991-01-03	2	9  

Command to make a grid:
gmt xyz2grd test.dat -Gtest.grd -R1991-01-01/1991-01-03/0/2 -I86400/1 -f0T,1x,2f

Result of gmt grd2xyz test.grd:
662688000	2	NaN
662774400	2	NaN
662860800	2	NaN
662688000	1	NaN
662774400	1	NaN
662860800	1	NaN
662688000	0	NaN
662774400	0	NaN
662860800	0	NaN

First and second columns are ok, but third column contains only NaNs. But replacing x on y in -f option (-f0T,1y,2f) third column contains right values. GMT version from git, ff4ef5c

**Comment by PaulWessel** [comment] 2019-12-26 07:22
The problem is not the z column but the longitude column being in the 2nd position - this caused a longitude check to go crazy.  Addressed in pull request #2345.

**Comment by seisman** [comment] 2019-12-26 15:42
Fixed in #2345.

**Closed by seisman** 2019-12-26 15:42 UTC
