### ISSUE TITLE
Feature request on PI

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#314] opened 2019-01-14 20:14 UTC
**Description of the desired feature**

See the command below:
```
gmt psxy -R-12pi/12pi/0/10 -JX10c/5c -Bxaf -Byaf -Sc1c -Gblack > test.ps << EOF 
3pi 5
EOF
```

Output figure:
![image](https://user-images.githubusercontent.com/3974108/51137961-e826a900-180d-11e9-8c8c-1cbf08c4f7cc.png)

Expected behaviors:
1. It's more intuitive if -Bxaf can annotate the x axis **with `pi`** in this case.
2. `pi` in the input table seems not recognized.

**Comment by joa-quim** [comment] 2019-01-14 20:44
This feature request as a flaw. It should be #3.14 and not #314

**Comment by PaulWessel** [comment] 2019-01-14 20:47
I agree, the pi stuff post-dates the implementation of auto intervals.

**Comment by PaulWessel** [comment] 2019-02-01 15:11
Despite agreeing above, the problem is that the automatic algorithm is tricky and based on font size of numbers and follows a set pattern.  I think if you want to specify a region in terms of pi then you may also have to specify your annotation intervals for now.
As for accepting 3pi as input I think this would add too much overhead of checking since we would need to implement what 3pi/4 etc should result in.  I think most people do not have data in that format.

**Comment by joa-quim** [comment] 2023-07-23 19:25
I think this issue is bagging to be closed.

**Comment by Esteban82** [comment] 2024-03-08 16:47
Closing?

**Comment by joa-quim** [comment] 2024-03-08 16:49
Yep.

**Closed** 2024-03-08 16:52 UTC
Labels: feature request
