### ISSUE TITLE
filter1d -L is redundant

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#40] opened 2018-08-27 00:11 UTC
This option is superseded by the global **-g** and must go, though maintaining backward compat.

**Comment by PaulWessel** [comment] 2018-09-22 05:04
We need to make a test to show this.  It is not obvious how -L and -g syntax would be and we have no actual example of the use.

**Comment by meghanrjones** [comment] 2021-01-25 17:52
The behavior is different for **-L** versus **-g**. It seems likely that the behavior differs because for **-g** the segmentation happens before filtering, whereas for **-L** the data are filtered first but no records are outputted in the data gap, although I have not confirmed this in the source code. Here is a rough example that shows the different results (needs a remote file in the cache directory at ~/.gmt/cache/):

```
head -n 360 ~/.gmt/cache/MaunaLoa_CO2.txt > ML_1.txt
tail -n 300 ~/.gmt/cache/MaunaLoa_CO2.txt >> ML_1.txt
gmt begin filter1d_ex1 pdf
    gmt set TIME_SYSTEM RD0001
    gmt filter1d ML_1.txt -Fg5 -V > CO2_trend.txt
    gmt filter1d ML_1.txt -Fg5 -L1 -V > CO2_trend_L.txt 
    gmt filter1d ML_1.txt -Fg5 -gx1 -V > CO2_trend_g.txt
    gmt plot ML_1.txt -Sc0.1 -Wred
    gmt plot CO2_trend.txt -Sc0.1 -Wblue
    gmt plot CO2_trend_L.txt -Sc0.1 -Wblack
    gmt plot CO2_trend_g.txt -Sc0.1 -Wgreen
gmt end show
```
I think we should keep **-L** and close the issue.

**Comment by PaulWessel** [comment] 2021-01-25 19:01
Thanks @meghanrjones for checking this - I concur and will close the issue.

**Closed by PaulWessel** 2021-01-25 19:01 UTC
Labels: discussion
