### ISSUE TITLE
-N should be effective to line

### ISSUE THREAD

**Issue by wangliang1989** [GenericMappingTools/gmt#5766] opened 2021-09-16 09:44 UTC
It is easy to write a text outside the basemap with the option of '-N'. But it is very difficult to draw a line outside the basemap because '-N' is not effective to a line.

**Comment by PaulWessel** [comment] 2021-09-16 10:14
That is by design. We cannot control how far outside a region you might draw and this could exceed our 10x10 meter imaginary paper size.

**Comment by wangliang1989** [comment] 2021-09-16 10:25
you also cannot control how far outside a region I might write a text or plot a star and so on.  which could exceed your 10x10 meter imaginary paper size.

**Comment by PaulWessel** [comment] 2021-09-16 10:35
True, but the reason for -N was for text that straddled the map boundary so that they would not get clipped.  It is not a perfect solution but a practical one.

**Comment by wangliang1989** [comment] 2021-09-16 10:41
For example, I draw three some stars in a base map. Then I add some text outside the base map to explain every star. So I need to draw a line from the star to its text.

**Comment by PaulWessel** [comment] 2021-10-04 00:36
I understand, but the clipping of the line is deeply buried inside GMT as we need to worry about periodic data and lines exiting one side and entering the other. Your case may be Cartesian but we still have clipping at a deep level, making this not a very high priority to rewrite.

**Comment by joa-quim** [comment] 2024-03-13 21:02
Closing as not planned.

**Closed by joa-quim** 2024-03-13 21:02 UTC
Labels: feature request
