### ISSUE TITLE
gmt docs behavior on server installations

### ISSUE THREAD

**Issue by KristofKoch** [GenericMappingTools/gmt#498] opened 2019-03-12 10:47 UTC
**Description of the desired feature**

Have `gmt docs` behave differently on desktop and server installations.

* on desktop installations everything is fine.
* on server sessions there is no browser to open - therefore I'd like to suggest to display the URL to the online documentation and maybe a hint for the man page and a note that there is desktop environment detected. 

**Detailed …**

Currently `gmt docs` tries to open the default browser. While this is nice on desktop installations it understandably fails on server installations. 

```
$ gmt docs coast -J
sh: 1: xdg-open: not found
docs [ERROR]: Opening http://gmt.soest.hawaii.edu/doc/latest/coast.html#j in the default browser via xdg-open failed with error 32512
docs: No such file or directory
```

According to `xdg-open` man page: "xdg-open is for use inside a desktop session only."

As I normally SSH into a remote machine to work with GMT the current incarnation of `gmt docs` is almost useless to me. It fails in a way that is still usable but I guess this is accidental. 

While there are man pages I prefer working with the online documentation (better layout, links, easier to read). Therefore I would still appreciate the URL to the online documentation. This allows to easily call the URL on the local machine (Cmd-click in _iTerm_ on MacOS for example) while working on the remote machine.

**My suggestion**
```
$ gmt docs coast -J
You are working in a server environment. Try opening
http://gmt.soest.hawaii.edu/doc/latest/coast.html#j
in a web browser on your local machine. 
```

Your thoughts?

**Comment by joa-quim** [comment] 2019-03-12 16:51
Hmmm, this bit of code at the end of ``docs.c`` should have done almost what you propose. I wonder why the ``system`` command have not triggered that error case.
```
	sprintf (cmd, "%s %s", can_opener[k], URL);
	if ((error = system (cmd))) {
		GMT_Report (GMT->parent, GMT_MSG_NORMAL, "Opening %s in the default browser via %s failed with error %d\n", URL, can_opener[k], error);
		perror ("docs");
		Return (GMT_RUNTIME_ERROR);
	}
```

**Comment by KristofKoch** [comment] 2019-03-12 17:45
@joa-quim as far as I can see it did trigger (third line in my output). But it seems GMT assumes `xdg-open` to be present and doesn't check for it. This throws the first error message (`sh: 1: xdg-open: not found`) in my understanding.

**Comment by joa-quim** [comment] 2019-03-12 19:04
Sorry, you are right. It did trigger the error message. But to print what you propose we would have to know that it failed for that exact reason. That is, how could we know that ``You are working in a server environment.``?

**Comment by KristofKoch** [comment] 2019-03-12 19:59
Maybe check if `xdg-open` is installed? As it is hosted by the _freedesktop.org_ project as part of the `xdg-utils` I assume you only find it in desktop distributions. 

This can be done POSIX compliant with

```
command -v xdg-open
```
it will return nothing if not installed. Otherwise you will get the path back:

```
kristof@h2813222:~$ command -v xdg-open
kristof@h2813222:~$ command -v gmt
/usr/local/bin/gmt
kristof@h2813222:~$
```
Checking for desktop environments is a different beast. Most GUIs rely on an _X-Server_ so 
```
command -v Xorg
```
might be your friend. However they might use _Wayland_ or even more obscure solutions. So this is unreliable at best. 

As you rely on `xdg-open` for the function of `gmt docs` the safest bet might be just to check for `xdg-open` as described above and change my proposed wording to something less assertive and more informative as well:

```
$ gmt docs coast -J
We couldn't find the program "xdg-open" on which "docs" relies upon.
This is normal if you are working in a server environment. Just open
http://gmt.soest.hawaii.edu/doc/latest/coast.html#j
in a web browser on your local machine. 
```

**Comment by uleysky** [comment] 2019-03-13 11:06
In the server environment, there may be a command links or lynx. Maybe make this command customizable? With default value xdg-open.

**Comment by KristofKoch** [comment] 2019-03-13 11:59
Good point, @uleysky

**Comment by PaulWessel** [comment] 2019-03-13 19:51
We can try to strengthen this.  However, I do not think most GMT users are running GMT remotely on a server.  In fact, most of them are sitting on a Windows or OS X computer, and we are not calling xdg-open anyway.  If there is a system utility that can reveal you are running in a system where X11 cannot open then we could add such messages under an if/endif for UNIX.
We could also look at the error code returned by system.  E.g., https://stackoverflow.com/questions/5638321/why-child-process-returns-exit-status-32512-in-unix
but most likely the causes will be (1) xdg-open not installed and distant second (2) cannot open X11 for display.  Or am I wrong?

**Comment by uleysky** [comment] 2019-03-14 00:04
In case (1) system returns error code 127. This is return code of sh -c <command>, if command can't be found. In case (2), the return code will be return code of xdg-open. xdg-open can return 3 (A required tool could not be found) or 4 (The action failed). On one of my systems xdg-open return 3, if X11 is not available. On another xdg-open run links in this case )

I look at the gmt docs as a special version of the man command. Of course, you can always search for information on the Internet, but if you just need to remember something small, the man command is irreplaceable. The man command has two advantages: it is fast (it works right there in the terminal, there is no need to switch windows) and local (it does not depend on the Internet connection). So, I prefer to use the links as a browser for gmt doc, even if I work in a graphical environment.

**Comment by PaulWessel** [comment] 2019-03-14 00:18
At the very least we should probably list xdg-open as a prerequisite for Unix-like systems, similar to how ghostscript gs is a required executable for all.

**Comment by KristofKoch** [comment] 2019-03-14 12:44
@PaulWessel I think it isn't such a great idea to list `xdg-open` as a prerequisite. I run gmt exclusively on headless machines. No X11 or similar installed. So no point in having `xdg-open` available. 

My original point was that `gmt docs` fails on headless or remote machines. I do enjoy however the easy access to the web documentation it provides in form of the URL. Basically a special (nicer) form of the `man` pages as @uleysky said. 

Maybe the best idea is to not touch it at all and add a note to the documentation why there might be a problem with `xdg-open`?

**Comment by joa-quim** [comment] 2019-03-14 13:48
We could add an option to only print the URLs (both the local one and www) and not trying to open it.
Something like  ``gmt docs <module-name> -?``

**Comment by KristofKoch** [comment] 2019-03-14 16:18
A great idea, @joa-quim. Very useful on these seemingly rare installations like mine.

**Comment by PaulWessel** [comment] 2019-03-14 19:03
How about instead simply catching the system error and say xdg-open could not open (to stderr) and then print the URL?  I.e., instead of adding an option it may print

> docs: Could not execute xdg-open (missing|other reason)
> http://<theaddress/thefile.html

The current error message is too harsh.

**Comment by joa-quim** [comment] 2019-03-14 19:33
That was actually my first idea when this tread started (and not restricted to ``xdg-open`` only), but now @uleysky seems to want to capture the stdout to wrap it in a script.

**Comment by PaulWessel** [comment] 2019-03-14 20:03
And that would work since the warning goes to stderr and the URL goes to stdout.

**Comment by uleysky** [comment] 2019-03-15 00:34
I do not want to run the xdg-open. It will open the new tab in the browser, but in most cases I just need to quickly look at some option, for which the console browser is more convenient. So, the option to print links fits better. And another, to choose between local documentation and www. There are bad times when the internet is down )

**Comment by joa-quim** [comment] 2019-03-15 00:47
> And another, to choose between local documentation and www. There are bad times when the internet is down )

It always tries to load the local docs first. Only when it fails the www one is attempted.

**Comment by PaulWessel** [comment] 2019-03-15 00:53
I have no strong views on this.  If @uleysky does not want to have xdg-open handle the URL then there truly are only two ways:

1. Add a module option such as what @joa-quim suggested above
2. Add a GMT Default GMT_URL_OPENER that can be set to something else.

I am not convinced of the hardship of xdg-open creating a new tab with the documentation.  You read it and hit Command-W or similar to close the tab.  Presumably the alternative viewer also need some sort of exit key to end?

**Comment by joa-quim** [comment] 2019-03-15 15:44
I've created PR #510 that now would print (in my case it's not finding the local URL because ``GMT5_SHAREDIR`` is pointing to GMT5)

```
docs plot
         Error running the "cmd /c start" program. This may indicate that you are working in a
         server environment. Try open this URL in a web browser on your local machine.
         http://gmt.soest.hawaii.edu/doc/latest/plot.html
```
@uleysky Is this good enough for you or still prefer a program option?

**Comment by uleysky** [comment] 2019-03-15 23:45
@joa-quim, it does not allow you to select a browser if the xdg-open is installed. The option would be much more flexible.

**Comment by PaulWessel** [comment] 2019-03-17 21:04
Hi @uleysky, It would be helpful to understand exactly what you need (and why).  If I understand you correctly, you wish _gmt docs manpage_ to print the local (if installed) or remote URL to stdout and then you can use that with lynx or some other command-line browser.  Is that correct (which browser is it)? If so, what is the practical difference between quitting that browser versus closing the page in the fuller browser that xdg-open will use?  Don't both scenarios require a single keystroke?  I ask because this would seem to be the workflow of a very small subset of users so we would need a very good reason, i.e., the solution would accomplish something that cannot be done otherwise.  It sounds like we are no longer dealing with _what_ to do if xdg-open fails; it is now about not wanting xdg-open to do its job.

**Comment by uleysky** [comment] 2019-03-18 00:34
In short, because it is Linux. The xdg-open gives an unpredictable result in the general case. Let me describe in more detail. I have a three different installations of Linux. First, my home computer with X and firefox in the system. Second, my computer at work with X, but firefox installed locally and not in path, so xdg-open can't find it. Third, worstation(s) without X and without  xdg-open at all. Thus, the following situations arise
1) Home computer. xdg-open creates new tab in Firefox. Good for long reads, but if you need a quick look at the option, the slowness is somewhat annoying.
2) Home computer, ssh -X to work. Worst case, xdg-open try to launch winebrowser.
3) Home computer, ssh to work. Good, links is running.
4) ssh to workstation without xdg-open. Bad, nothing is running.
5) Work computer, same as 2)
6) Relatively rare situation, ssh -X from work to home. Same as 1), xdg-open creates new tab in local Firefox.

So, depending on where and how I work, there are four situations, from good to bad: links is running, new tab in firefox, nothing happens, an absolutely unnecessary program is launched. With -? option I'll just write a wrapper script with exactly the same behavior in all cases, doing what I need.

**Comment by PaulWessel** [comment] 2019-03-18 01:51
OK, since docs does not really have options I don't mind adding one that just prints the URL to stdout. However, it won't be -? since that is gmt speak for print usage.  Probably **-Q** for a "dry run".

**Comment by joa-quim** [comment] 2019-03-18 01:57
The problem with that naming is that it would be interpret as a request to show option **-Q** of module XXX. That's why I picked the ``?`` so that we could parse it as meaning "print the URL". If not ``-?`` we need to pick char that is not used as option in modules.

**Comment by PaulWessel** [comment] 2019-03-18 02:00
Right, which is why I brought up a new GMT Default setting instead. @uleysky can just as easily run

`export GMT_URL_OPENER=links gmt $*
`

in a script called linksdoc and run that browser instead of some option like

`links `gmt docs $@ -?`
`

**Comment by PaulWessel** [comment] 2019-03-18 02:02
Or it would simply be an option to docs:

`gmt docs -Q psbasemap -L`

you would not put **-Q** after psbasemap.

**Comment by joa-quim** [comment] 2019-03-18 02:05
Definitively prefer this. Gmtdefaults is too looong already.

**Comment by PaulWessel** [comment] 2019-03-18 02:08
OK, I will give this a test and report.  But going for coffee first and you will be asleep by the time I get back.

**Closed** 2019-03-18 03:26 UTC

**Comment by uleysky** [comment] 2019-03-18 06:10
Thanks!
