### ISSUE TITLE
Confused....

### ISSUE THREAD

**Issue by bjcoakley** [GenericMappingTools/gmt#586] opened 2019-03-29 01:40 UTC
I am attempting to use x2sys_list, x2sys_solve and x2sys_datalist to correct some gravity data, based on a crossover analysis from x2sys_cross.

The crossovers, external and internal, are in the correct locations and seems to be reasonable.

I am using the following script;

cat $allcoas > $TAG.coe.txt

gmt x2sys_list -Cgrav -T$TAG $TAG.coe.txt -E -N4 -FnTc -Vl > grav.coe.txt

gmt x2sys_solve grav.coe.txt -T$TAG -Cgrav -Et -Vl > $X2SYS_HOME/"$TAG"/"$TAG"_corrections.txt

gmt x2sys_datalist =$TAG/$TAG.lis -A -Flon,lat,grav -T$TAG -Vl > $TAG.corrected.grav.dat
exit

The x2sys_list program creates the attached file grav.coe.txt, which seems sensible, except it contains values for tracks with less than four crossovers. I would have thought invoking "-N4" would eliminate those.

[grav.coe.txt](https://github.com/GenericMappingTools/gmt/files/3020720/grav.coe.txt)

Feedback received through stdout also seems reasonable.

x2sys_list [INFORMATION]: Read crossover database from GRAVD.coe.txt...
x2sys_list [INFORMATION]: Found 56 pairs and a total of 6881 crossover records.
x2sys_list [INFORMATION]: Writing Data Table to Standard Output stream
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN01 [461].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN02 [13].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN07 [247].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN08 [77].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN09 [133].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AS01 [13].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AS02 [142].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AS03 [45].
x2sys_list [INFORMATION]: Crossovers from AN02 minus AN03 [11].
x2sys_list [INFORMATION]: Crossovers from AN02 minus AN07 [26].
x2sys_list [INFORMATION]: Crossovers from AN02 minus AS03 [1].
x2sys_list [INFORMATION]: Crossovers from AN03 minus AN03 [34].
x2sys_list [INFORMATION]: Crossovers from AN03 minus AN04 [1].
x2sys_list [INFORMATION]: Crossovers from AN03 minus AN05 [6].
x2sys_list [INFORMATION]: Crossovers from AN03 minus AS03 [16].
x2sys_list [INFORMATION]: Crossovers from AN04 minus AN05 [43].
x2sys_list [INFORMATION]: Crossovers from AN04 minus AS03 [1].
x2sys_list [INFORMATION]: Crossovers from AN04 minus AS04 [20].
x2sys_list [INFORMATION]: Crossovers from AN05 minus AN05 [225].
x2sys_list [INFORMATION]: Crossovers from AN05 minus AN06 [16].
x2sys_list [INFORMATION]: Crossovers from AN05 minus AN07 [42].
x2sys_list [INFORMATION]: Crossovers from AN06 minus AN06 [149].
x2sys_list [INFORMATION]: Crossovers from AN06 minus AN07 [177].
x2sys_list [INFORMATION]: Crossovers from AN06 minus AN08 [69].
x2sys_list [INFORMATION]: Crossovers from AN07 minus AN07 [164].
x2sys_list [INFORMATION]: Crossovers from AN07 minus AN08 [76].
x2sys_list [INFORMATION]: Crossovers from AN07 minus AS02 [2].
x2sys_list [INFORMATION]: Crossovers from AN08 minus AN08 [245].
x2sys_list [INFORMATION]: Crossovers from AN08 minus AN09 [20].
x2sys_list [INFORMATION]: Crossovers from AN09 minus AN09 [425].
x2sys_list [INFORMATION]: Crossovers from AN09 minus AS02 [41].
x2sys_list [INFORMATION]: Crossovers from AN09 minus AS06 [387].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS01 [254].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS02 [253].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS03 [117].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS04 [1].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS06 [247].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS07 [143].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS08 [67].
x2sys_list [INFORMATION]: Crossovers from AS02 minus AS02 [178].
x2sys_list [INFORMATION]: Crossovers from AS02 minus AS03 [8].
x2sys_list [INFORMATION]: Crossovers from AS02 minus AS06 [27].
x2sys_list [INFORMATION]: Crossovers from AS03 minus AS04 [148].
x2sys_list [INFORMATION]: Crossovers from AS04 minus AS04 [426].
x2sys_list [INFORMATION]: Crossovers from AS04 minus AS05 [16].
x2sys_list [INFORMATION]: Crossovers from AS04 minus AS07 [4].
x2sys_list [INFORMATION]: Crossovers from AS05 minus AS05 [254].
x2sys_list [INFORMATION]: Crossovers from AS06 minus AS06 [332].
x2sys_list [INFORMATION]: Crossovers from AS06 minus AS07 [58].
x2sys_list [INFORMATION]: Crossovers from AS06 minus AS08 [258].
x2sys_list [INFORMATION]: Crossovers from AS06 minus AS09 [2].
x2sys_list [INFORMATION]: Crossovers from AS07 minus AS07 [76].
x2sys_list [INFORMATION]: Crossovers from AS07 minus AS08 [142].
x2sys_list [INFORMATION]: Crossovers from AS08 minus AS08 [262].
x2sys_list [INFORMATION]: Crossovers from AS08 minus AS09 [106].
x2sys_list [INFORMATION]: Crossovers from AS09 minus AS09 [174].
x2sys_list [INFORMATION]: Output 56 pairs and a total of 6881 crossover records.

And results in the following file;
[GRAVD_corrections.txt](https://github.com/GenericMappingTools/gmt/files/3020730/GRAVD_corrections.txt)

x2sys_solve also appears to run normally;

x2sys_solve [INFORMATION]: Reading Data Table from file grav.coe.txt
x2sys_solve [INFORMATION]: Found 6881 COE records
x2sys_solve [INFORMATION]: Determine number of independent track clusters
x2sys_solve [INFORMATION]: 36 tracks form a single connected cluster
x2sys_solve [INFORMATION]: Number of unknowns is 36 and number of constraints is 1
x2sys_solve [INFORMATION]: Matrix equation N * a = b: (N = 37 x 37)
x2sys_solve [INFORMATION]: Before correction, mean and st.dev.: -0.305283 24.5485 
x2sys_solve [INFORMATION]: After correction, mean and st.dev. : 0.632937 24.5121
x2sys_solve [INFORMATION]: Writing Data Table to Standard Output stream

Though I would have though applying the corrections would result in a larger reduction in the st.dev. 

Finally running x2sys_datalist creates the file GRAVD.corrected.grav.dat. 
Which appears to contain the latitude, longitude and UNIX system time.

63.717479	210.931424	1247764648.00
 63.717558	210.919520	1247764653.00
 63.717637	210.907601	1247764658.00
 63.717708	210.895668	1247764663.00
 63.717764	210.883727	1247764668.00
 63.717796	210.871789	1247764673.00
 63.717796	210.859855	1247764678.00
 63.717760	210.847919	1247764683.00
 63.717683	210.835977	1247764688.00
 63.717563	210.824034	1247764693.00
 63.717402	210.812085	1247764698.00
 63.717206	210.800128	1247764703.00
 63.716983	210.788165	1247764708.00
 63.716743	210.776201	1247764713.00
 63.716496	210.764241	1247764718.00
 63.716254	210.752295	1247764723.00
 63.716027	210.740360	1247764728.00
 63.715820	210.728435	1247764733.00

The command line specifies "-Flon,lat,grav"

Everything appears to be running smoothly, but it is not achieving the result I am expecting.

Am I missing something? Again?

**Comment by PaulWessel** [comment] 2019-03-31 20:57
The **-N** option clearly needs some clarification and upgrade.  As implemented, it can be used to exclude any involvement of a leg that generated < _cutoff_ total crossings with all other tracks.  So the reason you are seeing A - B with 1 crossing is that both A and B cross other legs at least 4 times.  I will implement this upgrade:

**-N**_cutoff_[**+p**]

where the **+p** modifier would instead skip track pairs who generated less than _cutoff_ crossings - which is what you might have expected.

As for datalist output: Our x2sys tests all run fine and tests all these things, so a bit surprising.  Could you again make available what I need to recreate that last x2sys_datalist call?

**Comment by bjcoakley** [comment] 2019-04-08 16:10
I am experimenting more with this. Was on travel last week, so just getting back to it. More soon.

Small issue;
Running x2sys_init with a .def file works normally, but returns the following message;
x2sys_init [WARNING]: Found deprecated file extension .def, please rename to .fmt

Changing the extension on the file to .fmt, does not run and results in the following message;
x2sys_init [ERROR]: Unable to find definition file : /usr/local/share/x2sys/../COA/GRAVD.def

**Comment by bjcoakley** [comment] 2019-04-09 01:38
This is the script I am using;
#!/bin/csh 

setenv X2SYS_HOME ../COA

set TAG = $1

gmt set TIME_EPOCH 1970-01-01T00:00:00 TIME_UNIT s

set allcoas = $TAG/crossover-files/coa.all.txt

cat $allcoas > $TAG.coe.txt

gmt x2sys_list -Cgrav -T$TAG $TAG.coe.txt -E -N4 -FnTc -Vl > grav.coe.txt

gmt x2sys_report $TAG.coe.txt -A -Cgrav -T$TAG -Vl >  grav_report.txt

gmt x2sys_solve grav.coe.txt -T$TAG -Cgrav -Et -Vl > $X2SYS_HOME/"$TAG"/"$TAG"_corrections.txt

gmt x2sys_datalist =$TAG/$TAG.lis -Flon,lat,grav -T$TAG -Vl > $TAG.corrected.grav.txt

Here is the output it generates;

x2sys_list [INFORMATION]: Read crossover database from GRAVD.coe.txt...
x2sys_list [INFORMATION]: Found 55 pairs and a total of 6845 crossover records.
x2sys_list [INFORMATION]: Writing Data Table to Standard Output stream
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN01 [461].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN02 [13].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN07 [247].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN08 [77].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN09 [133].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AS01 [13].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AS02 [142].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AS03 [45].
x2sys_list [INFORMATION]: Crossovers from AN02 minus AN03 [11].
x2sys_list [INFORMATION]: Crossovers from AN02 minus AN07 [26].
x2sys_list [INFORMATION]: Crossovers from AN02 minus AS03 [1].
x2sys_list [INFORMATION]: Crossovers from AN03 minus AN03 [34].
x2sys_list [INFORMATION]: Crossovers from AN03 minus AN04 [1].
x2sys_list [INFORMATION]: Crossovers from AN03 minus AN05 [6].
x2sys_list [INFORMATION]: Crossovers from AN03 minus AS03 [16].
x2sys_list [INFORMATION]: Crossovers from AN04 minus AN05 [43].
x2sys_list [INFORMATION]: Crossovers from AN04 minus AS03 [1].
x2sys_list [INFORMATION]: Crossovers from AN04 minus AS04 [18].
x2sys_list [INFORMATION]: Crossovers from AN05 minus AN05 [225].
x2sys_list [INFORMATION]: Crossovers from AN05 minus AN06 [16].
x2sys_list [INFORMATION]: Crossovers from AN05 minus AN07 [42].
x2sys_list [INFORMATION]: Crossovers from AN06 minus AN06 [147].
x2sys_list [INFORMATION]: Crossovers from AN06 minus AN07 [176].
x2sys_list [INFORMATION]: Crossovers from AN06 minus AN08 [69].
x2sys_list [INFORMATION]: Crossovers from AN07 minus AN07 [164].
x2sys_list [INFORMATION]: Crossovers from AN07 minus AN08 [76].
x2sys_list [INFORMATION]: Crossovers from AN07 minus AS02 [2].
x2sys_list [INFORMATION]: Crossovers from AN08 minus AN08 [245].
x2sys_list [INFORMATION]: Crossovers from AN08 minus AN09 [20].
x2sys_list [INFORMATION]: Crossovers from AN09 minus AN09 [425].
x2sys_list [INFORMATION]: Crossovers from AN09 minus AS02 [41].
x2sys_list [INFORMATION]: Crossovers from AN09 minus AS06 [380].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS01 [254].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS02 [253].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS03 [117].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS06 [247].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS07 [143].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS08 [67].
x2sys_list [INFORMATION]: Crossovers from AS02 minus AS02 [178].
x2sys_list [INFORMATION]: Crossovers from AS02 minus AS03 [8].
x2sys_list [INFORMATION]: Crossovers from AS02 minus AS06 [27].
x2sys_list [INFORMATION]: Crossovers from AS03 minus AS04 [148].
x2sys_list [INFORMATION]: Crossovers from AS04 minus AS04 [414].
x2sys_list [INFORMATION]: Crossovers from AS04 minus AS05 [16].
x2sys_list [INFORMATION]: Crossovers from AS04 minus AS07 [4].
x2sys_list [INFORMATION]: Crossovers from AS05 minus AS05 [250].
x2sys_list [INFORMATION]: Crossovers from AS06 minus AS06 [326].
x2sys_list [INFORMATION]: Crossovers from AS06 minus AS07 [58].
x2sys_list [INFORMATION]: Crossovers from AS06 minus AS08 [258].
x2sys_list [INFORMATION]: Crossovers from AS06 minus AS09 [2].
x2sys_list [INFORMATION]: Crossovers from AS07 minus AS07 [74].
x2sys_list [INFORMATION]: Crossovers from AS07 minus AS08 [142].
x2sys_list [INFORMATION]: Crossovers from AS08 minus AS08 [263].
x2sys_list [INFORMATION]: Crossovers from AS08 minus AS09 [107].
x2sys_list [INFORMATION]: Crossovers from AS09 minus AS09 [173].
x2sys_list [INFORMATION]: Output 55 pairs and a total of 6845 crossover records.
x2sys_report [INFORMATION]: Read crossover database GRAVD.coe.txt...
x2sys_report [INFORMATION]: Found 40 pairs and a total of 3212 crossover records.
x2sys_report [INFORMATION]: Writing Data Table to Standard Output stream
gmt(40903,0x106e8a5c0) malloc: Incorrect checksum for freed object 0x7fb8af827000: probably modified after being freed.
Corrupt value: 0x40c287628f5c28f6
gmt(40903,0x106e8a5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort
x2sys_solve [INFORMATION]: Reading Data Table from file grav.coe.txt
x2sys_solve [INFORMATION]: Found 6845 COE records
x2sys_solve [INFORMATION]: Determine number of independent track clusters
x2sys_solve [INFORMATION]: 36 tracks form a single connected cluster
x2sys_solve [INFORMATION]: Number of unknowns is 36 and number of constraints is 1
x2sys_solve [INFORMATION]: Matrix equation N * a = b: (N = 37 x 37)
x2sys_solve [INFORMATION]: Before correction, mean and st.dev.: 0.0248293 4.09198 
x2sys_solve [INFORMATION]: After correction, mean and st.dev. : 0.301425 4.9543
x2sys_solve [INFORMATION]: Writing Data Table to Standard Output stream
gmt [INFORMATION]: GMT_Create_Options: Must expand list file =GRAVD/GRAVD.lis
x2sys_datalist [INFORMATION]: Your distance unit (e) implies geographic data; -fg has been set.
x2sys_datalist [INFORMATION]: Writing Data Table to Standard Output stream
x2sys_datalist [INFORMATION]: Reading track AN01
x2sys_datalist [INFORMATION]: Reading track AN02
x2sys_datalist [INFORMATION]: Reading track AN03
x2sys_datalist [INFORMATION]: Reading track AN04
x2sys_datalist [INFORMATION]: Reading track AN05
x2sys_datalist [INFORMATION]: Reading track AN06
x2sys_datalist [INFORMATION]: Reading track AN07
x2sys_datalist [INFORMATION]: Reading track AN08
x2sys_datalist [INFORMATION]: Reading track AN09
x2sys_datalist [INFORMATION]: Reading track AS01
x2sys_datalist [INFORMATION]: Reading track AS02
x2sys_datalist [INFORMATION]: Reading track AS03
x2sys_datalist [INFORMATION]: Reading track AS04
x2sys_datalist [INFORMATION]: Reading track AS05
x2sys_datalist [INFORMATION]: Reading track AS06
x2sys_datalist [INFORMATION]: Reading track AS07
x2sys_datalist [INFORMATION]: Reading track AS08
x2sys_datalist [INFORMATION]: Reading track AS09

The file containing crossovers;
[GRAVD.coe.txt](https://github.com/GenericMappingTools/gmt/files/3056797/GRAVD.coe.txt)

Output from x2sys_list;
[grav.coe.txt](https://github.com/GenericMappingTools/gmt/files/3056799/grav.coe.txt)

Output from x2sys_report;
[grav_report.txt](https://github.com/GenericMappingTools/gmt/files/3056801/grav_report.txt)

Output from x2sys_solve;
[GRAVD_corrections.txt]
(https://github.com/GenericMappingTools/gmt/files/3056803/GRAVD_corrections.txt)

Output from x2sys_datalist;
[GRAVD.corrected.grav.txt](https://github.com/GenericMappingTools/gmt/files/3056810/GRAVD.corrected.grav.txt)

As before, it appears to be putting out latitude, longitude and UNIX system time.

If I remove the "-Flon,lat,grav" option from the invocation of x2sys_datalist, it outputs all of the fields from the .trk file. 

For example;

63.717479	210.931424	1247764648.000	 56.01	NaN	 816.85
63.717558	210.919520	1247764653.000	 56.51	NaN	 841.32
63.717637	210.907601	1247764658.000	 57.11	NaN	 851.66
63.717708	210.895668	1247764663.000	 57.82	NaN	 871.29
63.717764	210.883727	1247764668.000	 58.64	NaN	 911.29
63.717796	210.871789	1247764673.000	 59.53	NaN	 930.72
63.717796	210.859855	1247764678.000	 60.47	NaN	 936.28
63.717760	210.847919	1247764683.000	 61.38	NaN	 932.11
63.717683	210.835977	1247764688.000	 62.21	NaN	 924.36
63.717563	210.824034	1247764693.000	 62.92	NaN	 925.12
63.717402	210.812085	1247764698.000	 63.44	NaN	 927.17
63.717206	210.800128	1247764703.000	 63.78	NaN	 923.86
63.716983	210.788165	1247764708.000	 63.90	NaN	 900.95 etc.

But the gravity (field 4) is unmodified from the source .trk files.

Also I find it surprising that the mean and std dev. are larger post-correction than before. This is substantially reduced from earlier iterations because I found a couple very large crossovers and removed the data from the offending .trk file.

Thanks

**Comment by bjcoakley** [comment] 2019-05-09 00:21
Any suggestions you can offer would be appreciated.

**Comment by PaulWessel** [comment] 2019-05-09 18:32
I am sorry to leave you hanging.  My plate is and has been overflowing this week but starting Wednesday next week life should return to normal and I will have time to examine this issue then.

**Comment by bjcoakley** [comment] 2019-05-09 19:01
No worries Paul. I understand you have a lot to do. I trust that you will get to it sooner or later.

**Comment by PaulWessel** [comment] 2019-05-26 20:13
Hi Bernie, I did fix some issues in x2sys_solve that makes me wonder how you even got to the end.  Basically, it read the input file assuming the same column types that your GRAVD.def file said, hence those times since start of track were assumed to be lon, lats and things looked weird.  However, after I fixed this I got basically the same result as you have, including the mean/std values before/after you reported.  I am concerned that your log printout shows a few fatal issues and hence I suspect maybe the downstream data files are not correct.  For instance, you have

> x2sys_report [INFORMATION]: Writing Data Table to Standard Output stream
> gmt(40903,0x106e8a5c0) malloc: Incorrect checksum for freed object 0x7fb8af827000: probably modified after being freed.
> Corrupt value: 0x40c287628f5c28f6
> gmt(40903,0x106e8a5c0) malloc: *** set a breakpoint in malloc_error_break to debug
> Abort

which I cannot reproduce.  However, I have not yet gotten to the x2sys_datalist issue where there may be some similar confusion about what the columns represent.  Will see if I can get to that today.

**Comment by bjcoakley** [comment] 2019-05-27 18:58
Paul thanks very much for your efforts to date. I am somewhat pleased to find it was not my basic ignorance at the root of the problem. 

I have been wondering if the differences between the airborne data and ship track data might be somehow the cause of this. Both data sets are sequential, but cruises are typically continuous. Airborne lines, often flown in sets, are also continuous, but may have substantial gaps between sets. For the GRAV-D data, these sets are grouped in geographical blocks that impose spatial order on the data, but might not be the best unit of analysis for crossovers.

I have updated to the most recent version of GMT from GitHub. I will try more with this and report back. I have 6.0.0_f5d3d08_2019.05.26

Thanks again.

**Comment by bjcoakley** [comment] 2019-05-27 21:27
I just re-ran the crossover analysis on the GRAV-D files with a few added Icebridge data in the mix.
The cross-overs are reasonable.
[AIRBORNE.coe.txt](https://github.com/GenericMappingTools/gmt/files/3224993/AIRBORNE.coe.txt)

I then ran the correction script I have written.

#!/bin/csh

setenv X2SYS_HOME ../COA

set TAG = $1

gmt set TIME_EPOCH 1970-01-01T00:00:00 TIME_UNIT s FORMAT_FLOAT_OUT %.6f

set allcoas = $TAG/crossover-files/coa.all.txt

awk '{if ($1 != "#" && $1 != ">"){printf"%s %s\n",$11,$12}}' $allcoas | gmt psxy -R-100/100/-100/100 -JX6.5i -Sc0.025 -Bg10a30/g10a30WeSn -Gred > $TAG/all.coa.plot.ps

pstopdf $TAG/all.coa.plot.ps
/bin/rm $TAG/all.coa.plot.ps

cat $allcoas > $TAG/$TAG.coe.txt

gmt x2sys_list -Cgrav -T$TAG $TAG/$TAG.coe.txt -E -FTcn -Vl > $TAG/grav.coe.txt

gmt x2sys_report $TAG/$TAG.coe.txt -Cgrav -T$TAG -Vl >  $TAG/grav_report.txt

gmt x2sys_solve $TAG/grav.coe.txt -T$TAG -Cgrav -Et -Vl > $X2SYS_HOME/"$TAG"/"$TAG"_corrections.txt

gmt x2sys_datalist =$TAG/$TAG.lis -L$X2SYS_HOME/"$TAG"/"$TAG"_corrections.txt -Flon,lat,grav -T$TAG -Vl > $TAG/$TAG.corrected.grav.txt

exit

The TAG in this case is AIRBORNE.

This is the output that resulted;

COA-correct AIRBORNE
x2sys_list [INFORMATION]: Read crossover database from AIRBORNE/AIRBORNE.coe.txt...
x2sys_list [INFORMATION]: Found 75 pairs and a total of 35366 crossover records.
x2sys_list [INFORMATION]: Writing Data Table to Standard Output stream
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN01 [461].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN02 [13].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN07 [247].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN08 [77].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AN09 [133].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AS01 [13].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AS02 [142].
x2sys_list [INFORMATION]: Crossovers from AN01 minus AS03 [45].
x2sys_list [INFORMATION]: Crossovers from AN01 minus IB-2011 [12].
x2sys_list [INFORMATION]: Crossovers from AN01 minus IB-2012 [92].
x2sys_list [INFORMATION]: Crossovers from AN02 minus AN03 [11].
x2sys_list [INFORMATION]: Crossovers from AN02 minus AN07 [26].
x2sys_list [INFORMATION]: Crossovers from AN02 minus AS03 [1].
x2sys_list [INFORMATION]: Crossovers from AN02 minus IB-2011 [56].
x2sys_list [INFORMATION]: Crossovers from AN02 minus IB-2012 [78].
x2sys_list [INFORMATION]: Crossovers from AN03 minus AN03 [34].
x2sys_list [INFORMATION]: Crossovers from AN03 minus AN04 [1].
x2sys_list [INFORMATION]: Crossovers from AN03 minus AN05 [6].
x2sys_list [INFORMATION]: Crossovers from AN03 minus AS03 [16].
x2sys_list [INFORMATION]: Crossovers from AN03 minus IB-2011 [2].
x2sys_list [INFORMATION]: Crossovers from AN03 minus IB-2012 [2].
x2sys_list [INFORMATION]: Crossovers from AN04 minus AN05 [43].
x2sys_list [INFORMATION]: Crossovers from AN04 minus AS03 [1].
x2sys_list [INFORMATION]: Crossovers from AN04 minus AS04 [18].
x2sys_list [INFORMATION]: Crossovers from AN05 minus AN05 [225].
x2sys_list [INFORMATION]: Crossovers from AN05 minus AN06 [16].
x2sys_list [INFORMATION]: Crossovers from AN05 minus AN07 [42].
x2sys_list [INFORMATION]: Crossovers from AN05 minus IB-2011 [57].
x2sys_list [INFORMATION]: Crossovers from AN05 minus IB-2012 [109].
x2sys_list [INFORMATION]: Crossovers from AN06 minus AN06 [147].
x2sys_list [INFORMATION]: Crossovers from AN06 minus AN07 [176].
x2sys_list [INFORMATION]: Crossovers from AN06 minus AN08 [69].
x2sys_list [INFORMATION]: Crossovers from AN06 minus IB-2011 [32].
x2sys_list [INFORMATION]: Crossovers from AN06 minus IB-2012 [85].
x2sys_list [INFORMATION]: Crossovers from AN07 minus AN07 [164].
x2sys_list [INFORMATION]: Crossovers from AN07 minus AN08 [76].
x2sys_list [INFORMATION]: Crossovers from AN07 minus AS02 [2].
x2sys_list [INFORMATION]: Crossovers from AN07 minus IB-2011 [26].
x2sys_list [INFORMATION]: Crossovers from AN07 minus IB-2012 [87].
x2sys_list [INFORMATION]: Crossovers from AN08 minus AN08 [245].
x2sys_list [INFORMATION]: Crossovers from AN08 minus AN09 [20].
x2sys_list [INFORMATION]: Crossovers from AN08 minus IB-2012 [98].
x2sys_list [INFORMATION]: Crossovers from AN09 minus AN09 [425].
x2sys_list [INFORMATION]: Crossovers from AN09 minus AS02 [41].
x2sys_list [INFORMATION]: Crossovers from AN09 minus AS06 [380].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS01 [254].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS02 [253].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS03 [117].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS06 [247].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS07 [143].
x2sys_list [INFORMATION]: Crossovers from AS01 minus AS08 [67].
x2sys_list [INFORMATION]: Crossovers from AS02 minus AS02 [178].
x2sys_list [INFORMATION]: Crossovers from AS02 minus AS03 [8].
x2sys_list [INFORMATION]: Crossovers from AS02 minus AS06 [27].
x2sys_list [INFORMATION]: Crossovers from AS02 minus IB-2012 [1].
x2sys_list [INFORMATION]: Crossovers from AS03 minus AS04 [148].
x2sys_list [INFORMATION]: Crossovers from AS04 minus AS04 [414].
x2sys_list [INFORMATION]: Crossovers from AS04 minus AS05 [16].
x2sys_list [INFORMATION]: Crossovers from AS04 minus AS07 [4].
x2sys_list [INFORMATION]: Crossovers from AS05 minus AS05 [250].
x2sys_list [INFORMATION]: Crossovers from AS06 minus AS06 [326].
x2sys_list [INFORMATION]: Crossovers from AS06 minus AS07 [58].
x2sys_list [INFORMATION]: Crossovers from AS06 minus AS08 [258].
x2sys_list [INFORMATION]: Crossovers from AS06 minus AS09 [2].
x2sys_list [INFORMATION]: Crossovers from AS07 minus AS07 [74].
x2sys_list [INFORMATION]: Crossovers from AS07 minus AS08 [142].
x2sys_list [INFORMATION]: Crossovers from AS08 minus AS08 [265].
x2sys_list [INFORMATION]: Crossovers from AS08 minus AS09 [108].
x2sys_list [INFORMATION]: Crossovers from AS09 minus AS09 [173].
x2sys_list [INFORMATION]: Crossovers from IB-2010 minus IB-2010 [1926].
x2sys_list [INFORMATION]: Crossovers from IB-2010 minus IB-2011 [6698].
x2sys_list [INFORMATION]: Crossovers from IB-2010 minus IB-2012 [5774].
x2sys_list [INFORMATION]: Crossovers from IB-2011 minus IB-2011 [2770].
x2sys_list [INFORMATION]: Crossovers from IB-2011 minus IB-2012 [7614].
x2sys_list [INFORMATION]: Crossovers from IB-2012 minus IB-2012 [2999].
x2sys_list [INFORMATION]: Output 75 pairs and a total of 35366 crossover records.
x2sys_report [INFORMATION]: Read crossover database AIRBORNE/AIRBORNE.coe.txt...
x2sys_report [INFORMATION]: Found 57 pairs and a total of 24036 crossover records.
x2sys_report [INFORMATION]: Writing Data Table to Standard Output stream
x2sys_solve [INFORMATION]: Reading Data Table from file AIRBORNE/grav.coe.txt
x2sys_solve [INFORMATION]: Found 35366 COE records
x2sys_solve [INFORMATION]: Determine number of independent track clusters
x2sys_solve [INFORMATION]: 42 tracks form a single connected cluster
x2sys_solve [INFORMATION]: Number of unknowns is 42 and number of constraints is 1
x2sys_solve [INFORMATION]: Matrix equation N * a = b: (N = 43 x 43)
x2sys_solve [INFORMATION]: Before correction, mean and st.dev.: -0.206148 18.0532 
x2sys_solve [INFORMATION]: After correction, mean and st.dev. : 0.258629 19.0559
x2sys_solve [INFORMATION]: Writing Data Table to Standard Output stream
gmt [INFORMATION]: GMT_Create_Options: Must expand list file =AIRBORNE/AIRBORNE.lis
x2sys_datalist [INFORMATION]: Your distance unit (e) implies geographic data; -fg has been set.
x2sys_datalist [ERROR]: X2SYS Correction table (../COA/AIRBORNE/AIRBORNE_corrections.txt) requires a column (time) not present in COE database or auxiliary columns

Again the standard deviation is increased after the correction. 

No complaints about the output from x2sys_list;

[grav.coe.txt](https://github.com/GenericMappingTools/gmt/files/3224999/grav.coe.txt)

The output from x2sys_report seems fine.

[grav_report.txt](https://github.com/GenericMappingTools/gmt/files/3224998/grav_report.txt)

The corrections file seems not unreasonable.

[AIRBORNE_corrections.txt]
(https://github.com/GenericMappingTools/gmt/files/3224982/AIRBORNE_corrections.txt)

But the file AIRBORNE.corrected.grav.txt is empty.

Maybe that is progress. I hope this is somehow illuminating of the issues.

**Comment by bjcoakley** [comment] 2019-07-13 17:39
Any chance 6.0 might fix this issue?

**Comment by PaulWessel** [comment] 2019-07-13 19:46
Not yet.  Note the error above:

> x2sys_datalist [ERROR]: X2SYS Correction table (../COA/AIRBORNE/AIRBORNE_corrections.txt) requires a column (time) not present in COE database or auxiliary columns

Perhaps you need to add time to your -Flon,lat,grav argument?

**Comment by joa-quim** [comment] 2024-03-13 20:14
I'm afraid this issue will need a new interested to be looked at. Closing it for now.

**Closed by joa-quim** 2024-03-13 20:14 UTC
Labels: longterm
