### ISSUE TITLE
Paper size for a map

### ISSUE THREAD

**Issue by frspin** [GenericMappingTools/gmt#199] opened 2018-12-03 08:12 UTC
In my proc for getting my map I use:

gmt set PS_PAGE_ORIENTATION=portrait
gmt set PS_MEDIA 700cx450c

this, with defining a region
region=-R7.27/8.27/43.5/44.0
and a projection
projection=-JM65c

give me a file with size 690x480 mm

After recent commit:

Reduce chance of PostScript clipping if exceeding canvas in modern mo…

my file size jumped to 1478x480 mm, with a left zone completely void.

Reversing 
#define GMT_PAPER_MARGIN	40	
to
#define GMT_PAPER_MARGIN	5

solve the problem.

Is this a bug or I am missing some other initialization?

Regards

Franco Spinelli

**Comment by frspin** [comment] 2018-12-03 08:30
Il 03/12/18 09:23, Paul Wessel ha scritto:
> Hm, I ran the 800+ tests before committing that PR and there were no
> changes, so could you please post the script you ran to get the problem?

It is attached to this mail

Regards

Franco Spinelli

**Comment by PaulWessel** [comment] 2018-12-03 16:48
Sorry, not seeing anything here or in the email?

**Comment by frspin** [comment] 2018-12-03 16:57
My fault. I have used email client for my answer.
Now I am writing from Web interface on Github

[mappa_100k.zip](https://github.com/GenericMappingTools/gmt/files/2640425/mappa_100k.zip)

Regards

Franco Spinelli

**Comment by seisman** [comment] 2018-12-03 18:08
@PaulWessel You can reproduce the bug using following simple code:
```
gmt begin map pdf
gmt basemap -JH65c -R7.27/8.27/43.5/44.0 -Bafg
gmt end
```

**Comment by seisman** [comment] 2018-12-03 18:40
OS: macOS 10.14.1
gmt version: 6.0.0_2a0f78d
gs version: 9.26

Full debug information with -Vd:
```
gmt [DEBUG]: Obtained the ppid from parent: 35488
gmt [DEBUG]: Enter: gmtinit_new_GMT_ctrl
gmt [DEBUG]: GMT->session.SHAREDIR = /usr/local/Cellar/gmt/HEAD-2a0f78d/share/gmt
gmt [DEBUG]: GMT->session.HOMEDIR = /Users/seisman
gmt [DEBUG]: GMT->session.USERDIR = /Users/seisman/.gmt [created]
gmt [DEBUG]: GMT->session.CACHEDIR = /Users/seisman/.gmt/cache [created]
gmt [DEBUG]: GMT: 0. Will try to fine subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt
gmt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
gmt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /Users/seisman/.gmt
gmt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /Users/seisman/.gmt/postscriptlight
gmt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /usr/local/Cellar/gmt/HEAD-2a0f78d/share/gmt/postscriptlight
gmt [DEBUG]: GMT: 5. gmt_getsharepath failed
gmt [DEBUG]: Map distance calculation will be Cartesian
gmt [DEBUG]: Exit:  gmtinit_new_GMT_ctrl
gmt [DEBUG]: Enter: New_PSL_Ctrl
gmt [DEBUG]: Exit:  New_PSL_Ctrl
gmt [DEBUG]: Enter: gmt_manage_workflow
gmt [DEBUG]: Exit : gmt_manage_workflow
gmt [DEBUG]: Enter: PSL_beginsession
gmt [DEBUG]: Exit : PSL_beginsession
gmt [DEBUG]: Enter: PSL_setdefaults
gmt [DEBUG]: Exit : PSL_setdefaults
gmt [DEBUG]: Enter: gmtlib_io_init
gmt [DEBUG]: Exit : gmtlib_io_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: The PROJ_GEODESIC set to Vincenty
gmt [DEBUG]: Enter: gmt_getdefaults
gmt [DEBUG]: Exit:  gmt_getdefaults
gmt [DEBUG]: Enter: gmtlib_plot_C_format
gmt [DEBUG]: Exit:  gmtlib_plot_C_format
gmt [DEBUG]: Enter: gmtinit_get_history
gmt [DEBUG]: Initialize FFTW with 8 threads.
gmt [DEBUG]: GMT_Create_Session initialized GMT structure
gmt [DEBUG]: Shared Library # 0 (core). Path = libgmt.dylib
gmt [DEBUG]: Loading core GMT shared library: libgmt.dylib
gmt [DEBUG]: Loading GMT plugins from: /usr/local/Cellar/gmt/HEAD-2a0f78d/lib/gmt/plugins
gmt [DEBUG]: Shared Library # 1 (supplements). Path = /usr/local/Cellar/gmt/HEAD-2a0f78d/lib/gmt/plugins/supplements.so
begin [INFORMATION]: Creating a workflow directory /Users/seisman/.gmt/sessions/gmt6.35488
begin [DEBUG]: The PROJ_GEODESIC set to Vincenty
begin [DEBUG]: Set session name to be map pdf -Vd
begin [DEBUG]: Begin Workflow.  PPID = 35488. Directory /Users/seisman/.gmt/sessions/gmt6.35488 created.
begin [DEBUG]: GMT now running in modern mode [PPID = 35488]
gmt [DEBUG]: Entering GMT_Destroy_Session
gmt [DEBUG]: Obtained the ppid from parent: 35488
gmt [DEBUG]: Enter: gmtinit_new_GMT_ctrl
gmt [DEBUG]: GMT->session.SHAREDIR = /usr/local/Cellar/gmt/HEAD-2a0f78d/share/gmt
gmt [DEBUG]: GMT->session.HOMEDIR = /Users/seisman
gmt [DEBUG]: GMT->session.USERDIR = /Users/seisman/.gmt [created]
gmt [DEBUG]: GMT->session.CACHEDIR = /Users/seisman/.gmt/cache [created]
gmt [DEBUG]: GMT: 0. Will try to fine subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt
gmt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
gmt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /Users/seisman/.gmt
gmt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /Users/seisman/.gmt/postscriptlight
gmt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /usr/local/Cellar/gmt/HEAD-2a0f78d/share/gmt/postscriptlight
gmt [DEBUG]: GMT: 5. gmt_getsharepath failed
gmt [DEBUG]: Map distance calculation will be Cartesian
gmt [DEBUG]: Exit:  gmtinit_new_GMT_ctrl
gmt [DEBUG]: Enter: New_PSL_Ctrl
gmt [DEBUG]: Exit:  New_PSL_Ctrl
gmt [DEBUG]: Enter: gmt_manage_workflow
gmt [DEBUG]: GMT now running in modern mode [PPID = 35488]
gmt [DEBUG]: Exit : gmt_manage_workflow
gmt [DEBUG]: Enter: PSL_beginsession
gmt [DEBUG]: Exit : PSL_beginsession
gmt [DEBUG]: Enter: PSL_setdefaults
gmt [DEBUG]: Exit : PSL_setdefaults
gmt [DEBUG]: Enter: gmtlib_io_init
gmt [DEBUG]: Exit : gmtlib_io_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: The PROJ_GEODESIC set to Vincenty
gmt [DEBUG]: Enter: gmt_getdefaults
gmt [DEBUG]: Reading GMT Default parameters from file: /Users/seisman/.gmt/sessions/gmt6.35488/gmt.conf
gmt [DEBUG]: Exit:  gmt_getdefaults
gmt [DEBUG]: Enter: gmtlib_plot_C_format
gmt [DEBUG]: Exit:  gmtlib_plot_C_format
gmt [DEBUG]: Enter: gmtinit_get_history
gmt [DEBUG]: Initialize FFTW with 8 threads.
gmt [DEBUG]: GMT_Create_Session initialized GMT structure
gmt [DEBUG]: Shared Library # 0 (core). Path = libgmt.dylib
gmt [DEBUG]: Loading core GMT shared library: libgmt.dylib
gmt [DEBUG]: Loading GMT plugins from: /usr/local/Cellar/gmt/HEAD-2a0f78d/lib/gmt/plugins
gmt [DEBUG]: Shared Library # 1 (supplements). Path = /usr/local/Cellar/gmt/HEAD-2a0f78d/lib/gmt/plugins/supplements.so
gmt [DEBUG]: Use PS filename /Users/seisman/.gmt/sessions/gmt6.35488/gmt_0.ps-
gmt [DEBUG]: get_current_panel: No current panel selected so not in subplot mode
psbasemap [DEBUG]: History: Process -JH65c
psbasemap [DEBUG]: History: Process -R7.27/8.27/43.5/44.0
psbasemap [DEBUG]: Map distance calculation will be using great circle approximation with authalic auxiliary latitudes and authalic (R_2) radius = 6371007.1809 m, in meter.
psbasemap [INFORMATION]: Constructing the basemap
psbasemap [WARNING]: Central meridian not given, default to 7.77
psbasemap [DEBUG]: Projected values in meters: -43492.7 43492.7 4.70842e+06 4.76003e+06
psbasemap [DEBUG]: Auto-frame interval for axis 0 item 0: d = 0.0833333  f = 0.0166667
psbasemap [INFORMATION]: Auto-frame interval for x-axis (item 0): a0.0833333f0.0166667g0.0833333
psbasemap [DEBUG]: Auto-frame interval for axis 1 item 0: d = 0.0333333  f = 0.0166667
psbasemap [INFORMATION]: Auto-frame interval for y-axis (item 0): a0.0333333f0.0166667g0.0333333
psbasemap [INFORMATION]: Map scale is 1.33824 km per cm or 1:133824.
psbasemap [DEBUG]: Running in PS mode modern
psbasemap [DEBUG]: Use PS filename /Users/seisman/.gmt/sessions/gmt6.35488/gmt_0.ps-
psbasemap [DEBUG]: Create hidden PS file /Users/seisman/.gmt/sessions/gmt6.35488/gmt_0.ps-
psbasemap [DEBUG]: No figure file /Users/seisman/.gmt/sessions/gmt6.35488/gmt.figures - nothing to do
psbasemap [DEBUG]: Got session name as map and default graphics formats as pdf
psbasemap [DEBUG]: Entering plot_map_gridlines
psbasemap [DEBUG]: Draw meridian = 7.33333 from 43.5 to 44
psbasemap [DEBUG]: Draw meridian = 7.41667 from 43.5 to 44
psbasemap [DEBUG]: Draw meridian = 7.5 from 43.5 to 44
psbasemap [DEBUG]: Draw meridian = 7.58333 from 43.5 to 44
psbasemap [DEBUG]: Draw meridian = 7.66667 from 43.5 to 44
psbasemap [DEBUG]: Draw meridian = 7.75 from 43.5 to 44
psbasemap [DEBUG]: Draw meridian = 7.83333 from 43.5 to 44
psbasemap [DEBUG]: Draw meridian = 7.91667 from 43.5 to 44
psbasemap [DEBUG]: Draw meridian = 8 from 43.5 to 44
psbasemap [DEBUG]: Draw meridian = 8.08333 from 43.5 to 44
psbasemap [DEBUG]: Draw meridian = 8.16667 from 43.5 to 44
psbasemap [DEBUG]: Draw meridian = 8.25 from 43.5 to 44
psbasemap [DEBUG]: Draw parallel = 43.5 from 7.27 to 8.27
psbasemap [DEBUG]: Draw parallel = 43.5833 from 7.27 to 8.27
psbasemap [DEBUG]: Draw parallel = 43.6667 from 7.27 to 8.27
psbasemap [DEBUG]: Draw parallel = 43.75 from 7.27 to 8.27
psbasemap [DEBUG]: Draw parallel = 43.8333 from 7.27 to 8.27
psbasemap [DEBUG]: Draw parallel = 43.9167 from 7.27 to 8.27
psbasemap [DEBUG]: Draw parallel = 44 from 7.27 to 8.27
psbasemap [DEBUG]: Exiting plot_map_gridlines
psbasemap [DEBUG]: plot_wesn_map_boundary n_sides = 4
psbasemap [DEBUG]: plot_wesn_map_boundary doing side 0 with flag = 1
psbasemap [DEBUG]: plot_wesn_map_boundary doing side 1 with flag = 0
psbasemap [DEBUG]: plot_wesn_map_boundary doing side 2 with flag = 0
psbasemap [DEBUG]: plot_wesn_map_boundary doing side 3 with flag = 10
psbasemap [DEBUG]: Current size of half-baked PS file /Users/seisman/.gmt/sessions/gmt6.35488/gmt_0.ps- = 42642.
psbasemap (Free_Ctrl): tried to free unallocated memory
psbasemap (Free_Ctrl): tried to free unallocated memory
psbasemap (Free_Ctrl): tried to free unallocated memory
psbasemap (gmtlib_free_tmp_arrays): tried to free unallocated memory
gmt [DEBUG]: Entering GMT_Destroy_Session
gmt [DEBUG]: Obtained the ppid from parent: 35488
gmt [DEBUG]: Enter: gmtinit_new_GMT_ctrl
gmt [DEBUG]: GMT->session.SHAREDIR = /usr/local/Cellar/gmt/HEAD-2a0f78d/share/gmt
gmt [DEBUG]: GMT->session.HOMEDIR = /Users/seisman
gmt [DEBUG]: GMT->session.USERDIR = /Users/seisman/.gmt [created]
gmt [DEBUG]: GMT->session.CACHEDIR = /Users/seisman/.gmt/cache [created]
gmt [DEBUG]: GMT: 0. Will try to fine subdir=postscriptlight stem = PSL_custom_fonts suffix=.txt
gmt [DEBUG]: GMT: 1. gmt_getsharepath trying current dir
gmt [DEBUG]: GMT: 2. gmt_getsharepath trying USERDIR /Users/seisman/.gmt
gmt [DEBUG]: GMT: 3. gmt_getsharepath trying USERDIR subdir /Users/seisman/.gmt/postscriptlight
gmt [DEBUG]: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /usr/local/Cellar/gmt/HEAD-2a0f78d/share/gmt/postscriptlight
gmt [DEBUG]: GMT: 5. gmt_getsharepath failed
gmt [DEBUG]: Map distance calculation will be Cartesian
gmt [DEBUG]: Exit:  gmtinit_new_GMT_ctrl
gmt [DEBUG]: Enter: New_PSL_Ctrl
gmt [DEBUG]: Exit:  New_PSL_Ctrl
gmt [DEBUG]: Enter: gmt_manage_workflow
gmt [DEBUG]: GMT now running in modern mode [PPID = 35488]
gmt [DEBUG]: Exit : gmt_manage_workflow
gmt [DEBUG]: Enter: PSL_beginsession
gmt [DEBUG]: Exit : PSL_beginsession
gmt [DEBUG]: Enter: PSL_setdefaults
gmt [DEBUG]: Exit : PSL_setdefaults
gmt [DEBUG]: Enter: gmtlib_io_init
gmt [DEBUG]: Exit : gmtlib_io_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: The PROJ_GEODESIC set to Vincenty
gmt [DEBUG]: Enter: gmt_getdefaults
gmt [DEBUG]: Reading GMT Default parameters from file: /Users/seisman/.gmt/sessions/gmt6.35488/gmt.conf
gmt [DEBUG]: Exit:  gmt_getdefaults
gmt [DEBUG]: Enter: gmtlib_plot_C_format
gmt [DEBUG]: Exit:  gmtlib_plot_C_format
gmt [DEBUG]: Enter: gmtinit_get_history
gmt [DEBUG]: Enter: gmt_hash_init
gmt [DEBUG]: Exit:  gmt_hash_init
gmt [DEBUG]: Exit:  gmtinit_get_history
gmt [DEBUG]: Initialize FFTW with 8 threads.
gmt [DEBUG]: GMT_Create_Session initialized GMT structure
gmt [DEBUG]: Shared Library # 0 (core). Path = libgmt.dylib
gmt [DEBUG]: Loading core GMT shared library: libgmt.dylib
gmt [DEBUG]: Loading GMT plugins from: /usr/local/Cellar/gmt/HEAD-2a0f78d/lib/gmt/plugins
gmt [DEBUG]: Shared Library # 1 (supplements). Path = /usr/local/Cellar/gmt/HEAD-2a0f78d/lib/gmt/plugins/supplements.so
end [DEBUG]: End Workflow.  PPID = 35488. Directory /Users/seisman/.gmt/sessions/gmt6.35488 removed.
end [DEBUG]: No figure file /Users/seisman/.gmt/sessions/gmt6.35488/gmt.figures - nothing to do
end [DEBUG]: Got session name as map and default graphics formats as pdf
end [INFORMATION]: Process GMT figure queue: 1 figures found
end [INFORMATION]: Processing GMT figure #0 [map pdf ]
end [DEBUG]: psconvert: /Users/seisman/.gmt/sessions/gmt6.35488/gmt_0.ps- -Tf -Fmap -A
end (gmtlib_free_tmp_arrays): tried to free unallocated memory
psconvert [DEBUG]: Complete partial PS file /Users/seisman/.gmt/sessions/gmt6.35488/gmt_0.ps-
psconvert [DEBUG]: Size of half-baked PS file = 42642.
psconvert [DEBUG]: Fattened up PS file /Users/seisman/.gmt/sessions/gmt6.35488/gmt_0.ps-
psconvert [INFORMATION]: Processing /Users/seisman/.gmt/sessions/gmt6.35488/gmt_0.ps-...
psconvert [INFORMATION]: Find HiResBoundingBox ...
psconvert [DEBUG]: Running: gs -q -dSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true '/Users/seisman/.gmt/sessions/gmt6.35488/gmt_0.ps-' 2> './psconvert_35491c.bb'
psconvert [INFORMATION]: Figure dimensions: Width: 4175.08 points [147.288 cm]  Height: 1131.64 points [39.9218 cm]
psconvert [DEBUG]: Delete ./psconvert_35491c.bb
psconvert [INFORMATION]: [589.806 2860.51 4764.89 3992.15]...
psconvert [WARNING]: gmt_gdalread failed to convert the proj4 string
(null)
 to WKT
psconvert [INFORMATION]: Convert to PDF...
psconvert [DEBUG]: Running: gs -q -dNOPAUSE -dBATCH -dPDFSETTINGS=/prepress -dDownsampleColorImages=false -dDownsampleGrayImages=false -dDownsampleMonoImages=false -dUseFlateCompression=true -dEmbedAllFonts=true -dSubsetFonts=true -dMonoImageFilter=/FlateEncode -dAutoFilterGrayImages=false -dGrayImageFilter=/FlateEncode -dAutoFilterColorImages=false -dColorImageFilter=/FlateEncode -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -sDEVICE=pdfwrite  -g41751x11317 -r720 -sOutputFile='map.pdf' -f'./psconvert_35491d.eps'
psconvert [DEBUG]: Delete ./psconvert_35491d.eps
psconvert [DEBUG]: Final input buffer length was 256
psconvert (gmtlib_free_tmp_arrays): tried to free unallocated memory
end [INFORMATION]: Destroying the current workflow directory /Users/seisman/.gmt/sessions/gmt6.35488
end [DEBUG]: Delete gmt.canvas.0
end [DEBUG]: Delete gmt.conf
end [DEBUG]: Delete gmt.frame
end [DEBUG]: Delete gmt.history.0
end [DEBUG]: Delete gmt.layers.0
end [DEBUG]: Delete gmt.session
end [DEBUG]: Delete gmt_0.ps-
end (gmtlib_free_tmp_arrays): tried to free unallocated memory
gmt [DEBUG]: Entering GMT_Destroy_Session
```

**Comment by joa-quim** [comment] 2018-12-03 18:49
Works fine for me too.

**Comment by frspin** [comment] 2018-12-03 19:34
Il 03/12/18 20:24, Paul Wessel ha scritto:
> I notice I get
> |psconvert [INFORMATION]: Figure dimensions: Width: 1927.57 points
> [68.0002 cm] Height: 1131.64 points [39.9218 cm] |
> 
> while you guys get
> 
> |psconvert [INFORMATION]: Figure dimensions: Width: 4175.08 points
> [147.288 cm] Height: 1131.64 points [39.9218 cm] |
> 
> and things fall apart from then on.
> 

Test program from DonDong Tian show the problem also on Ubuntu 18.04

gs -v show

GPL Ghostscript 9.26 (2018-11-20)
Copyright (C) 2018 Artifex Software, Inc.  All rights reserved.

Attached 2 files with 5 (as previous) and 40 (as new in github) for
GMT_PAPER_MARGIN

Regards

Franco Spinelli

**Comment by frspin** [comment] 2018-12-03 19:37
As usual no attach from mail
[map_5.pdf](https://github.com/GenericMappingTools/gmt/files/2640975/map_5.pdf)
[map_40.pdf](https://github.com/GenericMappingTools/gmt/files/2640976/map_40.pdf)
Regards

Franco Spinelli

**Comment by PaulWessel** [comment] 2018-12-03 20:03
What would be helpful is to run the script except for the final "gmt end" command and make a zipfile with the content of the gmt.##### under your ~/.gmt/sessions directory.  In my case I have

pwessel@macnut:~/.gmt/sessions/gmt6.563-> ls
gmt.canvas.0	gmt.conf	gmt.frame	gmt.history.0	gmt.layers.0	gmt.session	gmt_0.ps-

That stuff should let me better understand what is going on.

**Comment by seisman** [comment] 2018-12-03 20:09
@PaulWessel My session logs are attached.
[gmt6.39430.zip](https://github.com/GenericMappingTools/gmt/files/2641091/gmt6.39430.zip)

**Comment by frspin** [comment] 2018-12-04 15:51
And this is my session zipped, from my Ubuntu 18.04 and GS 9.26

Regards

Franco Spinelli
[gmt6.3635.zip](https://github.com/GenericMappingTools/gmt/files/2644742/gmt6.3635.zip)

**Comment by PaulWessel** [comment] 2018-12-05 18:47
I can reproduce the problem on Ubuntu so that means I can debug. @joa-quim, you did this successfully under Windows?

**Comment by PaulWessel** [comment] 2018-12-05 19:44
Very strange.  Now it fails the same way on OSX.  the bbox calculation returns 0 for both xmin,ymin now and hence no trimming on left, bottom.

**Comment by joa-quim** [comment] 2018-12-05 20:04
Yes. Just redid Dongdong example and works fine.

**Comment by PaulWessel** [comment] 2018-12-18 23:20
AGU meeting intervened and nothing got done.  The problem is real though and will try to understand why it fails 9and why it worked when I first implemented it!).

**Comment by PaulWessel** [comment] 2018-12-19 03:36
This **has** to be a bug in ghostscript.  I took @seisman example and used -B0 to just draw the map outline with no annotations or ticks.  Then I edited the PostScript to strip away all the definitions not used here and replaced our macro shorthands with original PostScript commands (moveto, rlineto, etc).  The minimalist file map.ps using only standard PostScript commands is attached.  Have a look at lines 25+26.  If you run the gs bounding box calculation as is you will get a BB width of 65.05 cm, matching the plot dimension + line widths.  However, if you comment out line 26 and uncomment 25 you suddenly get a crazy bounding box width of 145 cm.  The command I use is

`gs -q -dSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox map.ps 2>&1 | grep HiResBoundingBox | awk '{print 2.54*($4-$2)/72}'
`

which prints the BB width in cm.  The only differences between the two runs is that in the case that works I shift the origin by not quite 40 inches (47999 = 40*72/0.06 - 1) while the one that fails I use exactly 40 inches (48000).  Since the PostScript file otherwise is unchanged it must be a gs bug.

BTW, experimentation with the original example that @seisman submitted shows that any value for GMT_PAPER_MARGIN up to 8.75 inches works but larger values starts giving a wider and wider white left margin.  However, 8.75 is not a magic number - it is simple a value that works for that plot.  For other cases (like my simple example) it is different (i.e., 39.9991666667 inches worked fine).  This is

GPL Ghostscript 9.26 (2018-11-20) on OS X Mojave

Let me know if you can reproduce this using my map.ps file, especially @joa-quim who seems to not see the original issue.

[map.ps.zip](https://github.com/GenericMappingTools/gmt/files/2693138/map.ps.zip)

**Comment by remkos** [comment] 2018-12-19 09:52
I just tried your test with gs **9.25** on Mac OS 10.14.2, with alternatively line 25 and 26 commented.
In both cases the result of the HiResBoundingBox is **almost** the same:
%%HiResBoundingBox: 2879.236037 2879.063912 4723.307856 3973.895879 (line 25 uncommented)
%%HiResBoundingBox: 2879.171912 2878.991912 4723.242606 3973.841879 (line 26 uncommented)

This ought to be the proper behaviour.

**Comment by remkos** [comment] 2018-12-19 09:58
We might need to look at the code changes between gs 9.25 and 9.26 to figure what is going wrong.
What is exactly the HR-BB you get on the failing example?

**Comment by frspin** [comment] 2018-12-19 15:47
Il 19/12/18 04:36, Paul Wessel ha scritto:
> This *has* to be a bug in ghostscript. I took @seisman 
> <https://github.com/seisman> example and used -B0 to just draw the map 
> outline with no annotations or ticks. Then I edited the PostScript to 
> strip away all the definitions not used here and replaced our macro 
> shorthands with original PostScript commands (moveto, rlineto, etc). The 
> minimalist file map.ps using only standard PostScript commands is 
> attached. Have a look at lines 25+26. If you run the gs bounding box 
> calculation as is you will get a BB width of 65.05 cm, matching the plot 
> dimension + line widths. However, if you comment out line 26 and 
> uncomment 25 you suddenly get a crazy bounding box width of 145 cm. The 
> command I use is
> 
> |gs -q -dSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox map.ps 2>&1 | grep 
> HiResBoundingBox | awk '{print 2.54*($4-$2)/72}' |
> 
> which prints the BB width in cm. The only differences between the two 
> runs is that in the case that works I shift the origin by not quite 40 
> inches (47999 = 40*72/0.06 - 1) while the one that fails I use exactly 
> 40 inches (48000). Since the PostScript file otherwise is unchanged it 
> must be a gs bug.

I can confirm this on Ubuntu 18.04/64 bit with gs 9.26

Running command on file as is give 65.0547 as result
Running command on modified file as suggested give 145.821 as result

Franco Spinelli

**Comment by PaulWessel** [comment] 2018-12-19 17:06
47999: %%HiResBoundingBox: 2879.171912 2878.991912 4723.242606 3973.841879
48000: %%HiResBoundingBox: 589.805982 2879.063912 4723.307856 3973.895879

**Comment by joa-quim** [comment] 2018-12-19 17:43
I have 9.22 and confirm that it's behaving well (65.0547 vs 65.0548)

**Comment by PaulWessel** [comment] 2018-12-19 17:45
My laptop had gs 9.25 and like @remkos it worked fine.  Upgraded to gs 9.26 and that gives the failure.  I will report to ghostscript.

**Comment by PaulWessel** [comment] 2018-12-19 18:01
Turns out somebody had recently reported a bug for epstool which now gives the wrong bounding box for a file.  The gs people will not investigate since epstool is not theirs.  I added a comment to that bug report for our case which must be related and uses gs directly.  https://bugs.ghostscript.com/show_bug.cgi?id=700306

**Comment by remkos** [comment] 2018-12-20 08:45
If you want to investigate: I think the bug is in the ghostscript's function `make_bbox` in `base/gxscanc.c`

**Comment by meghanrjones** [comment] 2022-01-21 20:56
I am closing the issue based on tests with the latest ghostscript release and the GMT development branch. Please reopen if the problem appears again.

**Closed by meghanrjones** 2022-01-21 20:56 UTC
Labels: longterm
