### ISSUE TITLE
A private notification level for the developers

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#2697] opened 2020-02-09 00:07 UTC
**Description of the desired feature**

There are currently two types of messages that GMT needs to provide to users regardless of verbosity levels:

1. When a GMT module relies on other high-level software to carry out calculations, such as STRIPACK,  SSRFPACK,  and GDAL, we should report that.  For example, sphtriangulate says

	`==> The hard work is done by algorithms 772 (STRIPACK) & 773 (SSRFPACK) by R. J. Renka [1997] <==`

2. Another message is the data attribution messages issued when reading remote data sets produced by NASA, NOAA, Scripps, etc.  For instance, grdcut may say

	`earth_relief_03s: Earth Relief at 3x3 arc seconds tiles provided by SRTMGL3 (land only) [NASA/USGS].`

I think writing these messages can be simplified if we add internally a GMT_MSG_NOTE which is either always displayed (Even if **-Vq**) or at the same level as errors (so can be turned off with **-Vq**).

Somewhat related, I think the gmt splash screen should acknowledge the other open source libraries we use in general, such as netCDF, lib curl, PCRE, FFTW, GDAL, LAPACK, Ghostscript, FFFmpeg, gm, etc.

**Comment by joa-quim** [comment] 2020-02-09 00:26
Don't know about STRIPACK, SSRFPACK but we certainly do not want to print a message every time a GDAL code is used. On the other hand, acknowledge it in the splash screen would be fair.

**Comment by PaulWessel** [comment] 2020-02-09 00:27
Well, I am thinking a call such as what nearneighbor or gmtgdal does to a contained algorithm in GDAL should be notified by such a message.  Reading a grid via GDAL does not warrant that, but seems to me we cannot take credit for the NN gridding by not saying anything.

**Comment by joa-quim** [comment] 2020-02-09 00:39
It's not only reading through GDAL, we have also all the proj stuff. Sure we need acknowledge all the credit it deserves, but not on command line execute programs. Imagine QGis (or GRASS) doing that, it would be a never ending flood of text.

**Comment by PaulWessel** [comment] 2020-02-09 00:41
OK, fair enough.  We may then wish to add the S*PACK to the splash screen with the rest I think.  The data attributions will come from whatever module first accesses it.

**Comment by seisman** [comment] 2020-02-09 00:43
We may also add a list to README.md in the top directory.

**Comment by PaulWessel** [comment] 2020-02-09 00:44
Yes, that seems fair as well.  So a list of software acknowledgements, basically.

**Comment by PaulWessel** [comment] 2020-02-11 23:34
Just noting here that we have updated the BUILDING.md file with an acknowledgments section and updated the gmt splash screen to state the libraries we link against.  The initial feature request of a separate verbosity level is still undecided.

**Comment by PaulWessel** [comment] 2020-03-10 00:57
We don't use GhostScript as  library, but it is a pretty important tool for GMT.  Shall we add it to the gmt splash screen with the libs?
I think GraphicsMagic is not quite in the same category, but being supportive of other open source projects seems like a good thing to do. If we did this then the splash line becomes

`[Built with netCDF, GDAL, PCRE, FFTW, LAPACK, ZLI; uses Ghostscript and GraphicsMagic]`

**Comment by seisman** [comment] 2020-03-10 01:13
Sound a good idea, but don't forget ffmpeg.

The problem is, the line is a little too long for public releases. 
```
	GMT - The Generic Mapping Tools, Version 6.1.0 [64-bit] [8 cores]
	[Built with netCDF, GDAL, PCRE, FFTW, LAPACK, ZLIB; uses Ghostscript, GraphicsMagick and FFmpeg]
	(c) 1991-2020 The GMT Team (https://www.generic-mapping-tools.org/team.html).

Supported in part by the US National Science Foundation (http://www.nsf.gov/)
and volunteers from around the world.

GMT is distributed under the GNU LGPL License (http://www.gnu.org/licenses/lgpl.html).
```
Maybe better to have a short paragraph below the license statement?

**Comment by PaulWessel** [comment] 2020-03-10 02:35
Yes, that is better.  Yank the netCDF, etc and place after that license line.  It is too busy up front right now.

**Comment by PaulWessel** [comment] 2020-03-10 02:48
Getting back to the initial posting reason: Since (1) there are some messages, such as attribution for global grids, possibly others, maybe license stuff, that we should print out for all users, and (2) these are not warnings or detailed information or errors, but more like an FYI, and (3) we have no mechanism to do this within our _GMT_Report_ mechanism, and (4) the reason for using _GMT_Report_ is to avoid calling _fprintf_ when it is not appropriate (e.g., from MATLAB), I propose to add a verbosity level that is only accessible to developers (and thus not selectable by **-**V), that prints out unless **-Vq** is given, uses enum GMT_MSG_NOTE, and prints like this:

`grdimage [NOTE]:Earth Relief at 3x3 arc seconds tiles provided by SRTMGL3 (land only) [NASA/USGS]`

I think this needs to be done.  Objections?

**Comment by seisman** [comment] 2020-03-10 02:59
> add a verbosity level that is only accessible to developers 

What does this mean? Can users see these "note" messages?

**Comment by PaulWessel** [comment] 2020-03-10 03:04
Yes, they will always be printed except for **-Vq**. They are of the NOTE kind, separate from ERROR, WARNING, INFORMATION, etc.  It is just not a documented user-accessible setting via **-**V.  It is a separate category from the others: It is information, but not the kind like the things we currently call INFORMATION (which is very detailed verbose feedback).

**Comment by seisman** [comment] 2020-03-10 03:08
It seems a little annoying when earth relief grids are used multiple times in one plot.

**Comment by PaulWessel** [comment] 2020-03-10 03:24
Ah, but it is only the first time the file is _downloaded_.  Not when it is _used_.

**Comment by PaulWessel** [comment] 2020-03-10 03:25
We do this already but with GMT_Message because of the lack of a verbosity class for these types of messages.

**Comment by seisman** [comment] 2020-03-10 03:26
> Ah, but it is only the first time the file is _downloaded_. Not when it is _used_.

That's OK to me.

**Comment by seisman** [comment] 2020-03-14 02:13
Implemented in #2881. Closing?

**Comment by PaulWessel** [comment] 2020-03-14 02:15
Yes, forgot.

**Comment by seisman** [comment] 2020-03-14 18:10
> Yes, that is better. Yank the netCDF, etc and place after that license line. It is too busy up front right now.

Reopen the issue since we haven't done the acknowledgement part.

**Closed** 2020-03-15 00:19 UTC
