### ISSUE TITLE
grdtrack crashes when using -nl

### ISSUE THREAD

**Issue by nickywright** [GenericMappingTools/gmt#6299] opened 2022-02-04 06:56 UTC
Hi,

I'm having trouble with grdtrack using the -nl flag, where I get an Abort trap. It only occurs with -nl, and not with any of the other interpolation schemes. The flag works using GMT6.1.1, but not with GMT6.3.0. 

**Full script that generated the error**

```
gmt grdtrack input.txt -fg -nl GlobSed-v2.nc -V > output.txt
```
Here, `input.txt` contains coordinates in 2° increments (also failed at 1° and 0.1°), e.g.
-180 -90
-178 -90
-176 -90
-174 -90
-172 -90
-170 -90
etc

and `GlobSed-v2.nc` is global sediment thickness (also fails with ETOPO).

**Full error message**

```
Assertion failed: (node < G->header->size), function gmt_bcr_get_z, file gmt_bcr.c, line 297.
Abort trap: 6
```

**System information**

* Operating system: macOS Monterey 12.2
* GMT version: 6.3.0

Any help would be greatly appreciated!

**Comment by meghanrjones** [comment] 2022-02-04 19:04
Can you please clarify the purpose of the profile with all the latitudes at -90? These seem redundant, so it would help to know the intended output for grdtrack before debugging.

```
gmt project -C-180/-90 -E-160/-90 -G2d -N -o0-1 > points.txt
cat points.txt
gmt begin test png
    gmt subplot begin 2x1 -Fs3c
        gmt plot points.txt -Sc0.1c -Gred -R-180/180/-90/-40 -Js-45/-90/40/? -B -fg
        gmt plot points.txt -Sc0.2c -Gred -JH? -B -Rg -fg -c
    gmt subplot end
gmt end show
```
```
-180    -90
-178    -90
-176    -90
-174    -90
-172    -90
-170    -90
-168    -90
-166    -90
-164    -90
-162    -90
-160    -90
```

![test](https://user-images.githubusercontent.com/14077947/152587915-c062f82b-cdf3-4154-a977-906cc1a7aaa1.png)

**Comment by PaulWessel** [comment] 2022-02-04 19:16
Think that bug was fixed a few weeks ago but I cannot find the link to the issue.  I can reproduce the crash in 6.3.0 but it is not a problem in master.

**Comment by meghanrjones** [comment] 2022-02-04 19:22
> Think that bug was fixed a few weeks ago but I cannot find the link to the issue. I can reproduce the crash in 6.3.0 but it is not a problem in master.

Does this work for you? I get the same crash as @nickywright when building from the master branch.

```
gmt --version
gmt project -C-180/-90 -E-160/-90 -G2d -N -o0-1 > points.txt
gmt grdtrack -G@earth_relief_01d points.txt -V -nl -fg > output.txt
```

```
6.4.0_48425a9_2022.02.04
grdtrack [INFORMATION]: Processing input grid(s)
grdtrack [INFORMATION]: netCDF grid /Users/meghanj/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd has no default CPT.
grdtrack [INFORMATION]: Reading grid from file /Users/meghanj/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd
grdtrack [INFORMATION]: gmt_grd_BC_set: Called with a pad < 2; skipped.
grdtrack [INFORMATION]: Reading Data Table from file points.txt
grdtrack [INFORMATION]: Writing Data Table to Standard Output stream
Assertion failed: (node < G->header->size), function gmt_bcr_get_z_fast, file gmt_bcr.c, line 256.
test.sh: line 3: 12057 Abort trap: 6           gmt grdtrack -G@earth_relief_01d points.txt -V -nl -fg > output.txt
```

**Comment by PaulWessel** [comment] 2022-02-04 19:28
Yes, works for me...

**Comment by PaulWessel** [comment] 2022-02-04 19:29
```
gmt grdtrack -G@earth_relief_01d points.txt -V -nl -fg > output.txt
grdtrack [INFORMATION]: Processing input grid(s)
grdtrack [INFORMATION]: netCDF grid /Users/pwessel/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd has no default CPT.
grdtrack [INFORMATION]: Reading grid from file /Users/pwessel/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd
grdtrack [INFORMATION]: gmt_grd_BC_set: Called with a pad < 2; skipped.
grdtrack [INFORMATION]: Reading Data Table from file points.txt
grdtrack [INFORMATION]: Writing Data Table to Standard Output stream
grdtrack [INFORMATION]: Sampled 11 points from grid /Users/pwessel/.gmt/server/earth/earth_relief/earth_relief_01d_p.grd (360 x 180)
```

**Comment by meghanrjones** [comment] 2022-02-04 19:32
I see, it failed for me because I was compiling with `-DDEBUG`.

**Comment by PaulWessel** [comment] 2022-02-04 19:35
How does that change it?

**Comment by meghanrjones** [comment] 2022-02-04 19:41
> How does that change it?

I think that assert statements are disabled by default in CMake release mode (e.g., https://stackoverflow.com/questions/34302265/does-cmake-build-type-release-imply-dndebug and https://stackoverflow.com/questions/22140520/how-to-enable-assert-in-cmake-release-mode).

**Comment by nickywright** [comment] 2022-02-05 03:31
@meghanrjones, sorry I should've said my points are 2° (or 0.1°) globally! I agree that all the points at 90°S are a little redundant, it was just the first few lines of my file. I'm using grdtrack to get sediment thickness/etopo values at X grid spacing (it's part of the [pybacktrack](https://github.com/EarthByte/pyBacktrack/tree/paleo-depth-reconstruction) workflow).

**Comment by PaulWessel** [comment] 2022-02-08 18:58
There are two problems that this example illustrates:

1. GMT defaults to pixel registration for remote grids.  This is in general fine, but for **grdtrack** it poses a problem.  Input points beyond the s/n node boundaries (which are |90-0.5*yinc|) are "outside the grid" and hence needs a boundary pad even for bilinear sampling.  For remote grids used in **grdtrack** I think we should default to gridline registration unless the user specifies a registration.
2. The crash I can fix by requiring a boundary pad for pixel grids.

@nickywright, I assume GlobSed-v2.nc is a pixel-registered global grid?

**Comment by nickywright** [comment] 2022-02-08 23:10
Hi @PaulWessel, [GlobSed-v2.nc](https://www.ngdc.noaa.gov/mgg/sedthick/) is gridline registered:

output from grdinfo:
```
GlobSed-v2.nc: Title: Produced by grdmath
GlobSed-v2.nc: Command: grdclip GlobSed_v2.nc -Sb0/0 -GGlobSed-v2.nc
GlobSed-v2.nc: Remark:
GlobSed-v2.nc: Gridline node registration ued [Geographic grid]
GlobSed-v2.nc: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
GlobSed-v2.nc: x_min: -180 x_max: 180 x_inc: 0.0833333333333 (5 min) name: longitude n_columns: 4321
GlobSed-v2.nc: y_min: -90 y_max: 90 y_inc: 0.0833333333333 (5 min) name: latitude n_rows: 2161
GlobSed-v2.nc: z_min: 0 z_max: 18333.6972656 name: z
GlobSed-v2.nc: scale_factor: 1 add_offset: 0
GlobSed-v2.nc: format: netCDF-4 chunk_size: 131,136 shuffle: on deflation_level: 3
```


I just compiled GMT from source (gmt version `6.4.0_d592d1a-dirty_2022.02.08`) and it still seems to be crashing, sorry!

```
ERROR: Caught signal number 11 (Segmentation fault: 11) at
0   libgmt.6.4.0.dylib                  0x000000010349e7a0 gmt_bcr_get_z + 368
1   ???                                 0x00007f8ffab9f044 0x0 + 140256363540548
Stack backtrace:
0   libgmt.6.4.0.dylib                  0x000000010358c828 sig_handler_unix + 216
1   libsystem_platform.dylib            0x00007ff80288de2d _sigtramp + 29
2   ???                                 0x000000000000000d 0x0 + 13
3   libgmt.6.4.0.dylib                  0x00000001037b6cf5 grdtrack_sample_all_grids + 165
4   libgmt.6.4.0.dylib                  0x00000001037b504f GMT_grdtrack + 21135
5   libgmt.6.4.0.dylib                  0x000000010347d464 GMT_Call_Module + 2180
6   gmt                                 0x0000000102de33b1 main + 1841
7   dyld                                0x000000010694d4fe start + 462
```

**Comment by meghanrjones** [comment] 2022-02-15 23:36
This should be fixed completely now by https://github.com/GenericMappingTools/gmt/pull/6322

**Closed by meghanrjones** 2022-02-15 23:36 UTC
Labels: bug
