### ISSUE TITLE
Surface: wrong error when breakline vectors are only 2D

### ISSUE THREAD

**Issue by jratike80** [GenericMappingTools/gmt#2268] opened 2019-12-09 21:48 UTC
If surface command is run with the breakline option (-D) and the breakline vectors have only XY coordinates, then surface prints misleading errors claiming that missing Z coordinates are in the point data, not in the breakline.

```
gmt surface savad.xyz -T0.25 -R633661.66/647110.33/6864853.99/6882303.99 -I5 -Dbreakline_2D.shp -Goutputi.tif=gd:GTiff+ctiled=yes+ccompress=deflate+cpredictor=3

surface [ERROR]: Mismatch between actual (2) and expected (3) fields near line 356 in file savad.xyz
surface [ERROR]: Mismatch between actual (2) and expected (3) fields near line 357 in file savad.xyz
surface [ERROR]: Mismatch between actual (2) and expected (3) fields near line 358 in file savad.xyz
```
There was nothing wrong with the point data file "savad.xyz" and the error disappeared when I finally discovered that I had to fix the breakline shapefile into 3D.

**Comment by PaulWessel** [comment] 2019-12-10 00:30
That is odd, since the saved.xyz is read first and then the other filename is passed to the reading function.  I cannot see in the code how it could happen, unless we have fixed this a while ago.  What version of GMT are you running?

**Comment by PaulWessel** [comment] 2020-01-04 19:44
Hi @jratike80 if you can produce an example with data that shows this error then I can debug it - otherwise I cannot do much.

**Comment by jratike80** [comment] 2020-01-04 22:31
[2d_shape_bug.zip](https://github.com/GenericMappingTools/gmt/files/4022581/2d_shape_bug.zip)

Try

`gmt surface 01.011.1.001.csv -R687780/689960/6902320/6903750 -I10 -D01.011.1.001_2d.shp -G01.011.1.001.tif=gd:GTiff`

3D version of the lake boundary shapefile is included in the zip for comparison. I believe you could use any of your own boundary data by converting a 3D shapefile into 2D with a command like

`ogr2ogr -f "ESRI Shapefile" -dim XY 01.011.1.001_2d.shp 01.011.1.001.shp`

**Comment by PaulWessel** [comment] 2020-01-04 22:37
Thanks, I can reproduce the issue and will see what needs to be fixed.

**Comment by PaulWessel** [comment] 2020-01-05 00:39
We have updated the code to properly report the actual file that is failing. Related to this, we are adding a **+z**_value_ modifier to **-D** to set a constant z _value_ for breaklines that only have x,y or to override any z-values given.  This will be committed soon.  Thanks for the example.

**Closed by PaulWessel** 2020-01-05 00:39 UTC
