### ISSUE TITLE
HTML doc pages fail to render "#openModal"

### ISSUE THREAD

**Issue by claudiodsf** [GenericMappingTools/gmt#2205] opened 2019-12-03 10:41 UTC
Take a look at `plot` doc page:

https://docs.generic-mapping-tools.org/dev/plot.html

`-L` option has an `Example` link which is an anchor to `#openModal`.

The problem is that no modal window is opened and the example is just shown inline in the documentation.

**Comment by seisman** [comment] 2019-12-03 14:36
Duplicate of issue #2189.

**Closed** 2019-12-03 14:37 UTC
