### ISSUE TITLE
grdfilter -T option for generate 1D array

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#2483] opened 2020-01-21 06:27 UTC
The following command crashes (although take log2 of year doesn't make any sense):
```
$ gmt filter1d @MaunaLoa_CO2.txt -Fg1 -T2000/2010/1+b 
ERROR: Caught signal number 11 (Segmentation fault) at
0   libgmt.6.dylib                      0x000000010dd499c7 GMT_filter1d + 9623
1   ???                                 0x0000000000000008 0x0 + 8
Stack backtrace:
0   libgmt.6.dylib                      0x000000010db83037 sig_handler + 583
1   libsystem_platform.dylib            0x00007fff6ebc0b5d _sigtramp + 29
2   ???                                 0x0000000000000000 0x0 + 0
3   libgmt.6.dylib                      0x000000010dba1a1f GMT_Call_Module + 1919
4   gmt                                 0x000000010db77d23 main + 2051
5   libdyld.dylib                       0x00007fff6e9d53d5 start + 1
```

The "Generating 1D Array" section mentions **+b**, **+l** modifiers, but it's not clear if these modifiers is available to **grdfilter -T**.

**Comment by PaulWessel** [comment] 2020-01-21 07:08
I am fixing the crash right now.  You get the same crash with

gmt math -T2000/2010/1+b T =

The issue is that the logarithmic arrays expect a few things that perhaps are not explained:

1. log10 arrays expect the inc to be 1,2, or 3.  These command illustrate what output you get: gmt math -T1/100/1+l T =; gmt math -T1/100/2+l T =; gmt math -T1/100/3+l T =
2 log2 arrays expect the inc to be log2(inc), so 1 means we create equidistant spacing in 1 and get 1,2,4,8,16, while an inc of 2 means we get 1, 4, 16, 64, 256, etc.  The -Tmin/max selects the first of these inside the range.

Thus, the 2000/2010 contained no multiple of 2 and it found zero, but this gave no error...
Fixed in #2485.

**Closed** 2020-01-21 14:40 UTC
