### ISSUE TITLE
Clear discussion or remote data handling

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/gmt#3629] opened 2020-07-08 20:49 UTC
**Description of the desired feature**

The documentation of [Datasets](https://docs.generic-mapping-tools.org/6.1/datasets.html) accessible from the sidebar in the gmt documentation is a list starting with GSHHG, then DCW, then earth relief, and so on.  I think we should separate these somehow.  The GSHHG stuff is the now ancient story of how the GSHHG was put together.  It is a bit dated and I think this placement is way to prominent.  If is more of an insider view and technical story.  We should bury it deeper, possible via a link from the modules coast, landmask, and gshhg
The DCW section is better and more aimed at users.  It explains what you can do.  However, maybe both of these could be replaced with a document on coastlines that links to these and also includes some info on OpenStreetMap and @KristofKoch example.
Finally, I think the list of remote data should be replaced by a single file called remote-data.rst that starts with a preamble about what this is, what the active servers are, how to change that, how to minimize downloads, how we auto-delete and auto-update etc,  Full disclosure.  Then, we add in the earth-relief.rst, earth-age.rst files as sections and can avoid repetition on discussions such as resolutions and registartions.
Note that grdimage.rst has an include of .. include:: earth_relief.rst_ which only discusses the relief files.  I think this should be replaced with a link to the main remote dataset site, and same from grdview.

**Comment by PaulWessel** [comment] 2020-07-08 20:51
In fact, for now I think yanking the GSHHG and DCW from the Dataset listing and add them to modules is better until we start tackling openStreetMap more.

**Comment by seisman** [comment] 2020-07-08 21:40
> The GSHHG stuff is the now ancient story of how the GSHHG was put together. It is a bit dated and I think this placement is way to prominent. If is more of an insider view and technical story. We should bury it deeper, possible via a link from the modules coast, landmask, and gshhg
> The DCW section is better and more aimed at users. It explains what you can do.

Yes, I have the same feeling. Most users don't care about how the GSHHG were built, but there are some users (like me) who would be interested in these ancient stories. So maybe put the long story in the appendix of the cookbook?

> Finally, I think the list of remote data should be replaced by a single file called remote-data.rst that starts with a preamble about what this is, what the active servers are, how to change that, how to minimize downloads, how we auto-delete and auto-update etc, Full disclosure. Then, we add in the earth-relief.rst, earth-age.rst files as sections and can avoid repetition on discussions such as resolutions and registartions.
> Note that grdimage.rst has an include of .. include:: earth_relief.rst_ which only discusses the relief files. I think this should be replaced with a link to the main remote dataset site, and same from grdview.

Agreed.

> In fact, for now I think yanking the GSHHG and DCW from the Dataset listing and add them to modules is better until we start tackling openStreetMap more.

Not sure it's a good idea. GSHHG and DCW are used in so many modules, e.g., coast, grdlandmask, and DCW is also used in **-R** option (e.g., `-RCN`).

**Comment by PaulWessel** [comment] 2020-07-08 22:26
Yes, DCW is a bit wider in that sense. GSHHS is pretty restricted.

**Comment by joa-quim** [comment] 2020-07-08 22:45
GSHHG is the biggest hurdle to build GMT on Unix. Every-time there was a problem installing GMT during the GMT/GMTSAR coursers the culprit was GSHHG. Even to me, when I start building GMT in that suffering environment the shit always come from the fact it's a separate product. On Windows, and for years, GSHHG has come with the installers. Never there was a report about troubles because of it.

We will not update GSHHG so we simply should merge it back to the GMT source tree (I never really liked the separation idea).

**Comment by PaulWessel** [comment] 2020-07-08 22:48
Those are also in the macos bundle. The only problem installing GSHHG seems to be for people who are not using any of the establish repos and are building from source.  Even ubuntu has 2.3.7 so even the most hamstrung Linux distro users can install dcw and gshhg taht way and then build GMT from source.  They would then need to specify those paths.

**Comment by PaulWessel** [comment] 2020-07-08 22:52
Of course, the GSHHG discussion used to be an appendix in the cookbook from day 1, but got elevated as "data" the last few years.

**Comment by joa-quim** [comment] 2020-07-08 22:57
Yes, I'm referring to the situation when one builds from source (otherwise it's just an *install me*). But then it's a fact, separate GSHHG (and DCW) it's pain.

**Comment by KristofKoch** [comment] 2020-07-09 13:41
From an end-user point of view I'd expect to have coastlines and borders built-in. 

They even have their own module (coast) which is non-functional without GSHHG and/or DCW. As GMT is mainly aimed at "Earth, Ocean, and Planetary Science" I would guess that almost every GMT installation needs those as well. 

Why not change the way GSHHG and DCW are handled?

* Just merge it into GMT (as @joa-quim proposed).
* If you install from a repo it is installed via the classic dependency way (status quo). 
* If you build from source it is handled like the other datasets via the `@earth_something`-handle behind the scenes (for those "hamstrung Linux distro users" as @PaulWessel put it).

This way no user interaction is required and there should be less problems during installation. 

Regarding the documentation I side with @seisman – this is great background knowledge. Maybe better placed in an appendix in the cookbook but interesting history of GSHHG none the less. It is easy to forget that GSHHG is way older than all those online mapping applications like OSM, Google/Apple Maps etc. which we all now take for granted.

**Comment by PaulWessel** [comment] 2020-07-09 19:24
An installer can be put together that has all the pieces, this is what the win and macos installers do.  If you want GSHHG and DCW to be merged into GMT I take that to mean you want those datasets to be included in the git hub repo (since they are separate now).  The github repo for GSHHS stores the ascii files of the polygons used to derive the netcdf files.  We are talking another 1 Gb of stuff.  Then tehre is all the GMT4-level software used to do the processing and build the netcdf files.  Or do you mean that the netcdf files for gshhg and dcw should be added to the gmt github? That would be much less, but now we large binary files in the repo and as updates still happen to these data there will be bloat.  Nevermind that we do hope to build GSHHG3 from OpenSTreetMap once the postdoc is onboard.
So I am not convinced that merging DCW and GSHHG into GMT at the repo level is a good idea.

**Comment by joa-quim** [comment] 2020-07-10 10:42
Then ``pscoast`` could offer to download and install the nc files in the right place. And cmake recipe have a rule to do the same.

**Comment by PaulWessel** [comment] 2020-07-10 18:41
Yes, I suppose if we can download 40 Gb of SRTM tiles we can manage to do tiny coastline files (~80 Mb).  Since for 99.99% of users they are the only user of their computer, makes no big difference to place them in .gmt versus some system directory.  It is not like 100 users on a mainframe will duplicate GMT coasts 100 times...

So the _gmt_init_shore_ function would just have to check if installed, and if not launch a libcurl call.  I suppose it could be granular to only get the resolution requested.

**Comment by joa-quim** [comment] 2020-07-10 18:59
> tiny coastline files (~80 Mb).

Nope, *only* ~55 MB.

But the idea is to smooth the biggest trouble (other than dependencies) when people try to build GMT. What GMT can do is to print a message with instruction on what do to download and install those files. I think this is better than download it under the hood because user could select the server where to download from, and on the other hand he/she would know why he's waiting for.

**Comment by PaulWessel** [comment] 2020-07-10 19:04
Add DCW to get ~80Mb I think?
We have gmt get who recently got an ugrade to download data, e.g.

gmt get -Ddata=earth -I2m

Gets all the earth data up to 2m resolution, leaving the larger files on the server.  We could add

gmt get -Ddata=coast

**Comment by joa-quim** [comment] 2020-07-11 17:46
Yes, looks good but it still should be proposed by fist time ``pscoast`` usage. The other case is when we build from ``cmake``. Then, if running tests is selected we get an error when the coastlines are not available. Maybe release this constraint and warn that they can also be downloaded after build.

**Comment by KristofKoch** [comment] 2020-07-11 19:32
@joa-quim would you mind elaborating why you prefer the user installing GSHHG/DCW by himself instead of having GMT taking care of this?

**Comment by joa-quim** [comment] 2020-07-11 19:40
Because downloading 80 Mb may take some time and user may think the program is not working (even if a message is printed). Second, because it may offer different servers for the user pick from (we will soon have at least 2 or 3).
Anyway, ``pscoast`` would print the exact command that user has to run.

**Comment by KristofKoch** [comment] 2020-07-11 20:02
If I understand correctly GSHHG/DCW is only missing if the user installs from source. The installers include it already and installation via packet managers have it as dependencies. 

From my own experience the problem isn’t getting GSHHG/DCW on the user’s system but to let GMT/cmake know where to find it there. This problem would still exist with your approach. Maybe I’m missing something?

**Comment by joa-quim** [comment] 2020-07-11 20:13
Yes, I referred to that case as well. In fact we have two situations. One is to get the coastlines stored in its right place at build time. That, the ideal one, has to be done by some cmake magic that I ignore. Tee second situation is the one when we choose not to run the tests, then we can NOT have the coastlines at build time. This is the case were ``gmt get -Ddata=coast`` would rescue the situation. After all, we can't run it before we build it :)

**Comment by seisman** [comment] 2020-07-11 20:38
GMT 6.1 now has a much simplified ConfigUserTemplate.cmake (only 6 settings) and also set COPY_GSHHG and COPY_DCW to TRUE by default. I expect users will have less problems with GSHHG and DCW.

**Comment by joa-quim** [comment] 2020-07-11 22:47
But that's the core of it. Because it needs that the user has already dl the files (not to mention the docs reading to learn that) and had set the paths. What we are talking is to get rid of this need once and for all.

**Comment by PaulWessel** [comment] 2020-07-11 23:58
I think we can have the best of both worlds: Still honor existing setup, preinstalled coasts, etc, but if we fail to find it there we say fuck it and download what is needed and place in ./gmt/gshhg and .gmt/dcw.  On demand, so only the particular resolution requested, hence worse case scenario is making a -Df map the first time [30 Mb].

**Comment by KristofKoch** [comment] 2020-07-12 13:59
I'd vote for @PaulWessel's solution: Honor what's there, if nothing is found just download it and put out a message to the user.

**Comment by PaulWessel** [comment] 2020-07-12 17:27
Thanks @KristofKoch, already implemented in #3645 and #3644 since it was so easy.

**Comment by meghanrjones** [comment] 2022-03-18 20:08
The downloading components of this issue were addressed by https://github.com/GenericMappingTools/gmt/pull/3645 and https://github.com/GenericMappingTools/gmt/pull/3644.

The documentation components were addressed by https://github.com/GenericMappingTools/gmt/pull/5938, https://github.com/GenericMappingTools/gmt/pull/5992, https://github.com/GenericMappingTools/gmt/pull/6021 (remote dataset documentation was added to separate repositories and the remote-dataset site that does not require releases).

**Closed by meghanrjones** 2022-03-18 20:08 UTC
